### ISSUE TITLE
This mod appears to be incompatible with anything involving particles on 1.15.2

### ISSUE THREAD

**Issue by Sunconure11** [TheRandomLabs/RandomPatches#101]
https://pastebin.com/u2X4fVnv

https://pastebin.com/VDXtmYGx

**Comment by TheRandomLabs** [comment]
This doesn't look like an issue with RandomPatches. Can you confirm if this occurs without?

**Comment by TheRandomLabs** [comment]
Assuming this isn't an issue. Let me know if it is!
