### ISSUE TITLE
Setting the right Iconpath 1.12.2

### ISSUE THREAD

**Issue by Silverrain2004** [TheRandomLabs/RandomPatches#102]
I have searched the Issues in the Past, but havent found any Clue how to set up the Iconpath
properly... so my questions are... can i use just the 256x or did i have to use all 3 ?
I have used "Itlt" and it was pretty easy.. there was a Folder with the name itlt there you can put
your PNG, set it up in your config and its finished.
But RandomPatches dont have such a Folder for this, witch is a little Difficult to set up. Now i have made 3 PNG Files with 256x, 64x, and 32x. I deinstalled "Itlt" and have made a new Folder with the Name "Icons". Now i have written in the config... Icons:256x.png and so on  .. becouse that is the Folder... but no Icons are showed... so can i have an example how to set it up right?

**Comment by TheRandomLabs** [comment]
It's a path relative to the Minecraft instance directory, so you would need `Icons/256x.png`.
