### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by NielsPilgaard** [TheRandomLabs/RandomPatches#103]
The game crashes on startup with `randompatches-1.15.2-1.21.1.3` - Reverting to `randompatches-1.15.2-1.21.1.2` fixes the issue.

Crash report: https://gist.github.com/NillerMedDild/e08c05b45fd5ed1030fb789207af076c

### Versions
- Forge-1.15.2-31.2.9
- RandomPatches-1.15.2-1.21.1.3

**Comment by BedrockLegends** [comment]
I get the same crash as Above

**Comment by TheRandomLabs** [comment]
I have absolutely no idea what could be causing this, considering the only file I changed between the two versions is completely unrelated. I might try recompiling with a newer version of Forge.

**Comment by TheRandomLabs** [comment]
Can you see if this is fixed in the latest version?

**Comment by NielsPilgaard** [comment]
Sure thing, I'll test this evening.

**Comment by NielsPilgaard** [comment]
Works just fine now, thank you.
