### ISSUE TITLE
[Suggestion] Set the default world border and world boundary to 33,554,432 blocks instead of vanilla's 30,000,000

### ISSUE THREAD

**Issue by muzikbike** [TheRandomLabs/RandomPatches#105]
Currently, vanilla has the world boundary set at the rather arbitrary value of 30,000,000, which means that a few million perfectly playable chunks are made completely inaccessible. It seems fitting for the mod to move the world boundary (and default world border size) to 33,554,432 instead, to fully maximise the playable area of the world.

A (probably unsupported) config option could maybe also be added to push the world border out to 2,147,000,000 or so instead, as the world should, while glitchy, still be stable out to this point (assuming MC-185925 gets fixed in 1.16).

**Comment by TheRandomLabs** [comment]
I'm not sure if those last three million blocks would be worth the effort. 😛
