### ISSUE TITLE
[Feature Request] Fabric 1.16 Version

### ISSUE THREAD

**Issue by ghost** [TheRandomLabs/RandomPatches#112]
Hello,
I know that there is a fabric version for 1.15 but can you please update it to work with 1.16
thank you have a nice day.

**Comment by TheRandomLabs** [comment]
https://www.curseforge.com/minecraft/mc-mods/randompatches-fabric
Should be up there soon. It only has the read and login timeouts for now.

**Comment by ghost** [comment]
Thanks!!!!

**Comment by ghost** [comment]
Sorry but the page you provided isn't valid,
maybe it's a curseforge thing but just wanted to let you know.

**Comment by TheRandomLabs** [comment]
It wasn't approved yet. Works now.
