### ISSUE TITLE
My users nearly always time out after exactly one minute, implies this config isn't applying?

### ISSUE THREAD

**Issue by onlyamonth** [TheRandomLabs/RandomPatches#114]
Minecraft 1.15.2
RandomPatches 1.15.2-1.22.0.0
Forge 31.2.21

Nearly every log in attempt for my users times out at 1 minute precisely, while their client is still "loading terrain". Are there any other steps I need to take to make this work?

**Comment by TheRandomLabs** [comment]
See #94. I'm currently not sure how to proceed. 🤷
