### ISSUE TITLE
Multiple crashes with latest update (1.16.1-22.1.0)

### ISSUE THREAD

**Issue by Shindur** [TheRandomLabs/RandomPatches#115]
A lot of users have been getting consistent crashes in the Enigmatica 6 modpack with the latest release of this mod.
It crashes with the TickNextTick list out of synch error - crash report from a user in the Enigmatica discord attached. In this particular crash he states he was flying around with an elytra.

[crash-2020-07-26_23.34.15-server.txt](https://github.com/TheRandomLabs/RandomPatches/files/4979990/crash-2020-07-26_23.34.15-server.txt)

**Comment by TheRandomLabs** [comment]
Sorry, I made an oversight because of a minor change in 1.14.4. Let me know if it's fixed now!
