### ISSUE TITLE
Possible Conflict with Dungeon Crawl

### ISSUE THREAD

**Issue by Camawama** [TheRandomLabs/RandomPatches#117]
game
[RandomPatches ServerTickList Transformer]: Patching method: <init> (<init>)
  <log4j:Event logger="Dungeon Crawl" timestamp="1596689117220" level="INFO" thread="Worker-Main-16">
    <log4j:Message><![CDATA[Building Dungeon at (193 / 48 / 193), 5 layers, Theme: 0, 0]]></log4j:Message>
  </log4j:Event>

monitor
Process Monitor
XML_ERROR_PARSING

**Comment by TheRandomLabs** [comment]
As far as I can tell, this does not lead to any actual problems. Let me know otherwise! :)
