### ISSUE TITLE
Failed to transform class: net.minecraft.tileentity.TileEntityPiston

### ISSUE THREAD

**Issue by SirOMGitsYOU** [TheRandomLabs/RandomPatches#119]
Getting this error message when booting up my server.

Any ideas? - I saw a previous issue regarding this mentioning it maybe Ice and Fire, but I do not have this mod installed
https://hastebin.com/atemayotuf.rb

**Comment by TheRandomLabs** [comment]
Can I have a debug.log?

**Comment by SirOMGitsYOU** [comment]
Server didn't generate a debug.log but here is latest.log 
[latest.log](https://github.com/TheRandomLabs/RandomPatches/files/5123736/latest.log)
