### ISSUE TITLE
Config reset when using rpreload or restarting server [Fabric 1.16.2]

### ISSUE THREAD

**Issue by ghost** [TheRandomLabs/RandomPatches#120]
Everytime i change the config and use rpreload or restart server the config get's reset, and the randompatches.toml becomes empty (sometimes reset to default settings)

Here is the log:
[latest(1).log](https://github.com/TheRandomLabs/RandomPatches/files/5119068/latest.1.log)

**Comment by TheRandomLabs** [comment]
This may be an encoding issue. I cannot reproduce this, but let me know if using UTF-8 doesn't work.
