### ISSUE TITLE
Fix attack behavior bugs

### ISSUE THREAD

**Issue by Unknowneth** [TheRandomLabs/RandomPatches#123]
MC-147516 - Melee attacking mobs randomly stop attacking when they are too close to you
How to reproduce:
1.Spawn any melee attacking mobs other than Piglins or Hoglins
2.Stand still
3.Let them attack you
Observation: Mob randomly freezes
Expectation: They will continue attacking without stopping

MC-121706 - Skeletons don't look up or sideways when attacking, they only look forward
How to reproduce:
1.Spawn a skeleton with a bow
2.Let them shoot
3.Go to a higher or lower ground
Observation: their head rotation is fixed 0°
Expectation: They will adjust head rotations

MC-196449 - Piglins and Hoglins have pathfinding issues when attacking(Pre-1.16.3 versions)
How to reproduce:
1.Spawn a piglin or a Hoglin
2.Let them charge at you
3.When they are near, change positions
Observation: They freeze and analyze the last position you were at, then continue attacking once more
Expectation: They just run at you at full speed and not stop

MC-181937 - Vexes' head rotation are locked when attacking
How to reproduce:
1.Spawn a vex
2.Get the Vex to attack something
Observation: their head won't rotate, it is completely fixed to 0°
Expectation: they will rotate their heads to the the target's position

MC-170435 - Horse model is not always facing the right way(usually when the horse has a non player rider)
How to reproduce:
1.Spawn a horse jockey with a hostile mob riding it
2.Get the mob to target something
Observation: their body is incorrectly rotating
Expectation: the horse will rotate to where it is moving

**Comment by TheRandomLabs** [comment]
Moving MC-121706 and MC-170435 to #147.
