### ISSUE TITLE
RandomPatches 1.12.2-1.6.0.0 - Server

### ISSUE THREAD

**Issue by walker-dev** [TheRandomLabs/RandomPatches#13]
No crash log, fetched from
[debug.log](https://gist.githubusercontent.com/boosterdev/4ec14c97f1ffda972edbd7d09c02763a/raw/bd7d532f28093e1172a70994e1bdba933b943a5d/gistfile1.txt)

**Comment by ProsperCraft** [comment]
Same problem, clientside code on the server side - 
https://gist.github.com/ProsperCraft/6751cf29b273549189fc45a9a4278a30
