### ISSUE TITLE
[1.16] loginTimeout is in seconds, but it's actually counted in ticks, causing early disconnects

### ISSUE THREAD

**Issue by ViRb3** [TheRandomLabs/RandomPatches#131]
I'm not completely sure this is what happens, but a lot of people from the community are reporting early disconnects due to timeout while connecting to a server. Everybody reports that increasing the `loginTimeout` from `900` to `9000` fixes this issue. That's weird, because it's already in seconds, so that's 15 minutes. Or is it? As far as I can tell, the code actually reads it in ticks, which means a client has 45 seconds to connect or they get disconnected, which is very hard to do on a big modpack.

Source: https://github.com/TheRandomLabs/RandomPatches/blob/1.16/src/main/resources/patches/ServerLoginNetHandler.js

**Comment by TheRandomLabs** [comment]
I'll check this out tomorrow. :smile:

**Comment by TheRandomLabs** [comment]
You're right; I misdocumented the property. This is now fixed, and I've also increased the default login timeout to 1800 ticks (90 seconds).
