### ISSUE TITLE
Ability to rebind the "place against interactable block" functionality of Shift to something else

### ISSUE THREAD

**Issue by muzikbike** [TheRandomLabs/RandomPatches#132]
Similar to how the dismount key can be made to not be the same as sneaking with this mod. Sometimes I find that having to constantly place for example hopper chains, either I have to do it painfully slowly or precision twerk while placing.

**Comment by TheRandomLabs** [comment]
Unfortunately, this would have to be both client and server-sided, which doesn't fit in RandomPatches. Maybe I'll do it in a future mod some day. 😛
