### ISSUE TITLE
Ability to rebind or disable the double-tap to sprint functionality

### ISSUE THREAD

**Issue by muzikbike** [TheRandomLabs/RandomPatches#133]
relates to #75 and #132

This follows the forward movement key by default, but an ability to bind it to another key (as to have two different sprint keys) or disable it entirely would be handy since I don't use it in modern versions due to there being a dedicated sprint key, and it can get in the way of some precise movements.

**Comment by TheRandomLabs** [comment]
This is also in the 1.16.4 rewrite. :smile:
