### ISSUE TITLE
Fix MC-25512

### ISSUE THREAD

**Issue by muzikbike** [TheRandomLabs/RandomPatches#134]
Pretty obscure visual bug, until you find out it exists.

Note how in this screenshot, the character's sleeves are completely obscured by the worn chestplate:

![2020-11-28_01 12 40](https://user-images.githubusercontent.com/52297970/100490887-27ff8c80-3117-11eb-83be-bbd8ae5d2bed.png)

However, this is not visually represented on the first person arm, where it does not render at all:

![2020-11-28_01 13 19](https://user-images.githubusercontent.com/52297970/100490892-3e0d4d00-3117-11eb-9cb6-fdc417272a46.png)
![2020-11-28_01 13 36](https://user-images.githubusercontent.com/52297970/100490894-3fd71080-3117-11eb-9eb6-6a4ca91c1903.png)

(originally had this reported to the aether mod, since it adds gloves which do in fact render in the first person, but it was probably considered out of scope there and was resolved, and it probably would fit better in this mod anyway)

Bug tracker link: https://bugs.mojang.com/browse/MC-25512

**Comment by TheRandomLabs** [comment]
Closing this so I can keep track of it with #147.
