### ISSUE TITLE
Still getting "Moved too quickly!" errors on 1.12.2

### ISSUE THREAD

**Issue by Coloradohusky** [TheRandomLabs/RandomPatches#135]
Playing on a server I made, both server and client have it, and I set the speeds to max (well, almost max: 3.3999999521443642E38 and 1.79E308), but I'm still getting this error. Are there any mods that conflict with the speed limits? I have Ice and Fire, maybe that's the problem? Not really sure

**Comment by TheRandomLabs** [comment]
Ice and Fire takes control of the vehicle speed limit, but you can configure the normal and elytra speed limits in the next release. :smile:

**Comment by Coloradohusky** [comment]
Ah ok, I thought that had already been fixed, when looking at the description - but thanks! I'll take a look at Ice and Fire's config to see if I can fix it there

**Comment by TheRandomLabs** [comment]
So did I. 😄
