### ISSUE TITLE
[1.16..4] 1.22.1.10 crashes during early loading

### ISSUE THREAD

**Issue by bessiq** [TheRandomLabs/RandomPatches#139]
Forge 35.1.11
RandomPatches 1.16.4-1.22.1.10
crash report: https://hastebin.com/zigakatufu.rb

Let me know if you need further info. Thanks!

**Comment by TheRandomLabs** [comment]
Oh dear, I accidentally built with JDK 11.

**Comment by TheRandomLabs** [comment]
This should be fixed in the reupload of the same version. Thank you for reporting! :smile:
