### ISSUE TITLE
Possible incompatibility issue with the latest build of JEID and VanillaFix

### ISSUE THREAD

**Issue by Sunconure11** [TheRandomLabs/RandomPatches#14]
https://pastebin.com/FWeg4KCp

Upon loading the latest build of JEID with this mod, the game refuses to boot up, unless VanillaFix is forced to load first.

**Comment by ghost** [comment]
https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/39

**Comment by TheRandomLabs** [comment]
I couldn't reproduce this crash with VanillaFix 1.0.9-97, JustEnoughIDs 1.0.2-25 and RandomPatches 1.12.2-1.6.0.1, but I attempted a fix anyway. Could you try 1.6.0.2?

**Comment by Sunconure11** [comment]
Tried and still ran into this.

**Comment by VladimirMangos** [comment]
I can reproduce crash with 4 mods only combination:

JustEnoughIDs-1.0.2-25.jar
malisiscore-1.12.2-6.4.0.jar
randompatches-1.12.2-1.6.0.2.jar
VanillaFix-1.0.9-97.jar

Any subset of its not crash

**Comment by brisingraerowing** [comment]
I think it may be MalisisCore at fault here, as that uses a very outdated version of the Mixin library. Version 0.7.4, IIRC (CBA to look it up right now).

**Comment by TheRandomLabs** [comment]
Even so, I'll try to come up with a fix.

**Comment by TheRandomLabs** [comment]
https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/39#issuecomment-428461950

**Comment by VladimirMangos** [comment]
Related malisiscore issue https://github.com/Ordinastie/MalisisCore/issues/151

**Comment by VladimirMangos** [comment]
Fixed at JustEnoughIDs side
