### ISSUE TITLE
Is the version off on the latest release?

### ISSUE THREAD

**Issue by Letoric** [TheRandomLabs/RandomPatches#140]
I have randompatches-1.16.4-1.22.1.10.jar which I downloaded on the 9th at 10PM CST, you posted a new update yesterday (the 10th) that is using that version#

Is this a curseforge issue? Versioning issue? Am I going crazy somehow?

**Comment by TheRandomLabs** [comment]
My bad, I had to reupload the version, as I initially compiled it with the wrong JDK version. This (hopefully) won't happen again. :smile:
