### ISSUE TITLE
No Such Method 1.16.4, Forge 35.1.11+

### ISSUE THREAD

**Issue by ghost** [TheRandomLabs/RandomPatches#143]
Forge 35.1.11 and 35.1.13
MC 1.16.4
RandomPatches 1.16.4-1.22.1.10

Crash when setting icon ?, No Such Method

[Latest.log](https://pastebin.com/rBX3bbyM)

**Comment by TheRandomLabs** [comment]
Damn, I got this report before and tried to recompile with JDK 8, but it turns out that Gradle *still* used a different version of the JDK installed on my system. 😑
