### ISSUE TITLE
Fix MC-13187

### ISSUE THREAD

**Issue by muzikbike** [TheRandomLabs/RandomPatches#145]
This does not seem to be model based and is instead an issue with the rendering engine. Not a fan of this bug.

**Comment by TheRandomLabs** [comment]
Damn, I can't actually reproduce this one.

**Comment by muzikbike** [comment]
Screenshots?

**Comment by TheRandomLabs** [comment]
![image](https://user-images.githubusercontent.com/16755704/102712761-964efd80-4317-11eb-9963-4d3c2f4f8933.png)
Doesn't look nearly as opaque.

**Comment by TheRandomLabs** [comment]
Oh, it seems that I *can* reproduce it in vanilla Minecraft, but not with Forge.

**Comment by TheRandomLabs** [comment]
Wait, *what*? The rewritten version of RandomPatches seems to fix this issue somehow, but I never implemented anything of the sort... 😕

**Comment by TheRandomLabs** [comment]
Oh, I'm stupid. I just realised that I *did* and forgot about it. I was testing a line of code that I thought might fix it, but I forgot that I left it in. Needless to say, given how simple the fix is, I'm surprised Mojang hasn't fixed it yet. 😛
