### ISSUE TITLE
Crash on loading if forced world generation is enabled and conflicting with another world gen mod doing the same.

### ISSUE THREAD

**Issue by DWX12** [TheRandomLabs/RandomPatches#15]
Long story short, if there's another mod that also has a forced world gen setting enabled, the game will crash on loading. The only suggestion I have to avoid this issue is a warning, upon load, if RandomPatches can detect another mod is trying to force world gen as well.

I encountered this with Hexlands and am glad I had thought that this was the issue.

Great mod. Thank you or all of your hard work and effort, it's well appreciated.

**Comment by TheRandomLabs** [comment]
Could you elaborate? I had no problems generating a world with RandomPatches and Hex Lands with `forceHexGen` set to `true`.

**Comment by DWX12** [comment]
I'm sorry, this was meant for RandomTweaks. I apologize, they just look very similar, but thankfully you're the same mod author. I will post this over on that github and close this issue.
