### ISSUE TITLE
Dedicated server refuses to start-up?

### ISSUE THREAD

**Issue by nanonestor** [TheRandomLabs/RandomPatches#157]
As stated in subject - with Random Patches 2.1.0 (for Forge / minecraft 1.16.4) - Dedicated server running Forge 35.1.13 errors out attempting to start up.  latest.log and debug.log attached.  No crash report generates.
[latest (26).log](https://github.com/TheRandomLabs/RandomPatches/files/5756801/latest.26.log)
[debug (10).log](https://github.com/TheRandomLabs/RandomPatches/files/5756802/debug.10.log)

**Comment by TheRandomLabs** [comment]
Update your version of Performant.
