### ISSUE TITLE
[1.16.4] Media buttons pause the game

### ISSUE THREAD

**Issue by ocram9** [TheRandomLabs/RandomPatches#162]
When using the media buttons on my keyboard or mouse, the escape menu opens and my GUI gets toggled (pressing f1 basically). I have binded play/pause to a button on my mouse and is a fn+1 on my keyboard. Both cause this issue. I don't have these buttons bound to anything in Minecraft so they shouldn't activate anything. This only happens with media buttons because the button on my mouse that mutes discord doesn't do anything.

**Versions**
- Minecraft 1.16.4
- Forge 31.1.28
- Randompatches 2.1.0
- Mouse: g502 hero
- Keyboard: Sharkoon Skiller MECH SGK1

**Comment by TheRandomLabs** [comment]
Whoops, I don't believe I considered the mouse buttons when implementing these.
