### ISSUE TITLE
World loading crash

### ISSUE THREAD

**Issue by WeedTasteGood** [TheRandomLabs/RandomPatches#164]
Forge version: 35.1.28
MInecraft version: 1.16.4
Randompatches version: 2.1.5

Randompatches 1.16.4-2.1.5-forge.jar does not have such problem

No crash log is generated but here is a latest.log ( It seems that it's too long so I will post it in an external site)

https://docdro.id/MoDw6wb (You have to download the file to view the whole document)

Thanks!

**Comment by TheRandomLabs** [comment]
Does the crash occur without RandomPatches?

**Comment by WeedTasteGood** [comment]
> Does the crash occur without RandomPatches?

I am not a programmer/coder so I have zero knowledge about which mod is responsible for the crash. Crash occurs occasionally with or without the mod when I load into a new world (don't know about old ones).

**Comment by TheRandomLabs** [comment]
If the crash occurs without my mod, then I don't think it's my mod causing the issue.
