### ISSUE TITLE
[fabric] mod not working

### ISSUE THREAD

**Issue by SpacEagle17** [TheRandomLabs/RandomPatches#167]
After the last update 2.1.6 it seems like the mod doesn't work properly. The log shows that the mod is loaded (https://pastebin.com/XDc4dz4R). I have not changed anything (randompatches.toml : https://pastebin.com/KkX9t8Sc ). Some features don't work, maybe all of them, i couldn't try everything out. Example: cauldron and end portal block not rendering as intended.
![2021-01-06_11 52 19](https://user-images.githubusercontent.com/46494907/103761684-57a78b80-5017-11eb-9a9a-c7838a4bda12.png)
![2021-01-06_11 52 24](https://user-images.githubusercontent.com/46494907/103761689-58d8b880-5017-11eb-85a4-cbadb4f253b4.png)

**Comment by TheRandomLabs** [comment]
You've downloaded the Javadoc file.
