### ISSUE TITLE
Client titlebar and taskbar not displaying correctly

### ISSUE THREAD

**Issue by Letoric** [TheRandomLabs/RandomPatches#168]
The client is now showing a %2 or %s in the title bar, instead of the appropriate information. This started with version 2.1.5. The task bar icon is also not displaying correctly. You can replicate this by downloading ATM6, or ATM's Slice of Pi modpack, and then updating random patches.

**Comment by TheRandomLabs** [comment]
The 2.0.0 rewrite revamped the configuration, so they will have to be reconfigured.
