### ISSUE TITLE
Game crashed in 1.16.2 with 2.1.7

### ISSUE THREAD

**Issue by SpacEagle17** [TheRandomLabs/RandomPatches#170]
I have tried the latest version 2.1.7 in 1.16.2 and the game crashes after entering a world. The game loads perfectly until the title screen, and when you enter a world it crashes. Log: https://pastebin.com/f4qbTddv
I have tried 2.1.7 in 1.16.4 and it works perfectly fine

**Comment by SpacEagle17** [comment]
Sorry for submitting a lot of issues lately

**Comment by TheRandomLabs** [comment]
Update your version of Fabric Loader. It's all good; that's what the issue tracker is for.
