### ISSUE TITLE
game crashed in 1.16.4 fabric

### ISSUE THREAD

**Issue by SpacEagle17** [TheRandomLabs/RandomPatches#172]
i have just downloaded the latest versions of my different mods and it seems that minecraft crashes because of randompatches. I have removed the mod and minecraft doesn't crash.
log: https://pastebin.com/DmaiyTJd

**Comment by TheRandomLabs** [comment]
Does the crash occur consistently?

**Comment by SpacEagle17** [comment]
apparently not. Why does this not happen consistently?

**Comment by SpacEagle17** [comment]
I have tried it now multiple times and it didn't crash just the first 2 times today, then i removed it and reported the issue. Now it doesn't crash. Does that make sense according to the log?

**Comment by TheRandomLabs** [comment]
Yeah, the class loader is trying to generate metadata for a class, and in doing so, concurrent modification of the metadata cache occurs. I have no idea why this crash would be occurring, and I'm not sure if it's specific to my mod. If you can find a way to consistently reproduce it, let me know. 😄

**Comment by SpacEagle17** [comment]
Ok, i will close this for now
