### ISSUE TITLE
(Forge 1.16.4) Exception Ticking World

### ISSUE THREAD

**Issue by Darkfiend009** [TheRandomLabs/RandomPatches#175]
Minecraft: 1.16.4
Forge: 35.1.36
RandomPatches: 2.1.5

Server is receiving "Exception Ticking World" due to "TickNextTick list out of synch." If it is not a RandomPatches issue, i apologize. This particular crash report was a little difficult for me to understand.

Crash Report: https://pastebin.com/mPFyGC5C

**Comment by TheRandomLabs** [comment]
#142
It's not *caused* by RandomPatches, but RandomPatches fails to fix it. I've just realised that when porting the fix to 1.16.4, I forgot to update it properly.
