### ISSUE TITLE
Netty Epoll Server IO #0/FATAL Mixin apply failed randompatches

### ISSUE THREAD

**Issue by ivan-cavero** [TheRandomLabs/RandomPatches#177]
I have put the server-side mod in the latest version, with the server in 1.16.5 and it starts correctly, but when I enter the server it gives this error.
I don't know if it is my problem, if so what would be the solution?
The server-side mods are (all 1.16.5) :
- Blocklogger
- Carpet
- Carpet Extra
- Discord Fabric Whitelister
- Dynmap
- Fabric API
- Fabric Discord Link
- Fabric language kotlin
- FastFurnace
- Krypton
- Lazydfu
- Lithium
- MiniMOTD
- Phosphor
- TicTcas
- Watchtower
- and RandomPatches

`Netty Epoll Server IO #0/FATAL Mixin apply failed randompatches.mixins.json:packetsizelimits.PacketInflaterMixin -> net.minecraft.class_2532: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("CONSTANT") on net/minecraft/class_2532::getMaxCompressedPacketSize with priority 1000 cannot inject into net/minecraft/class_2532::decode(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V merged by me.steinborn.krypton.mixin.network.pipeline.PacketInflaterMixin with priority 1000 [PREINJECT Applicator Phase -> randompatches.mixins.json:packetsizelimits.PacketInflaterMixin -> Prepare Injections ->  -> constant$bgd000$getMaxCompressedPacketSize(I)I -> Prepare]
21.01 12:22:53 [Server] INFO org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("CONSTANT") on net/minecraft/class_2532::getMaxCompressedPacketSize with priority 1000 cannot inject into net/minecraft/class_2532::decode(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V merged by me.steinborn.krypton.mixin.network.pipeline.PacketInflaterMixin with priority 1000 [PREINJECT Applicator Phase -> randompatches.mixins.json:packetsizelimits.PacketInflaterMixin -> Prepare Injections ->  -> constant$bgd000$getMaxCompressedPacketSize(I)I -> Prepare]
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[fabric-server-launch.jar:?]
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[fabric-server-launch.jar:?]
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[fabric-server-launch.jar:?]
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[fabric-server-launch.jar:?]
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?]
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?]
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
21.01 12:22:53 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]
21.01 12:22:53 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
21.01 12:22:53 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
21.01 12:22:53 [Server] INFO at net.minecraft.class_2535.method_10760(class_2535.java:365) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at net.fabricmc.fabric.impl.networking.server.ServerLoginNetworkAddon.lambda$sendCompressionPacket$2(ServerLoginNetworkAddon.java:118) ~[13f320ee-1916-4141-9521-1af1e2531cf1.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:696) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:258) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:338) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.epoll.AbstractEpollChannel.doWriteBytes(AbstractEpollChannel.java:363) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytes(AbstractEpollStreamChannel.java:274) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteSingle(AbstractEpollStreamChannel.java:483) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:441) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:516) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:901) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1396) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:1013) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:248) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at net.minecraft.class_2535.doSendPacket(class_2535.java:605) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at net.minecraft.class_2535.mdcf6b1f$lambda$sendImmediately$rewrite$0$0(class_2535.java:582) ~[intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313) [intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [intermediary-server.jar:?]
21.01 12:22:53 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
21.01 12:22:53 [Server] INFO Jan 21, 2021 11:22:53 AM io.netty.util.concurrent.DefaultPromise notifyListener0
21.01 12:22:53 [Server] INFO WARNING: An exception was thrown by net.fabricmc.fabric.impl.networking.server.ServerLoginNetworkAddon$$Lambda$5001/0x0000000801136840.operationComplete()
21.01 12:22:53 [Server] INFO org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
21.01 12:22:53 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
21.01 12:22:53 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
21.01 12:22:53 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
21.01 12:22:53 [Server] INFO at net.minecraft.class_2535.method_10760(class_2535.java:365)
21.01 12:22:53 [Server] INFO at net.fabricmc.fabric.impl.networking.server.ServerLoginNetworkAddon.lambda$sendCompressionPacket$2(ServerLoginNetworkAddon.java:118)
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
21.01 12:22:53 [Server] INFO at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48)
21.01 12:22:53 [Server] INFO at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:696)
21.01 12:22:53 [Server] INFO at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:258)
21.01 12:22:53 [Server] INFO at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:338)
21.01 12:22:53 [Server] INFO at io.netty.channel.epoll.AbstractEpollChannel.doWriteBytes(AbstractEpollChannel.java:363)
21.01 12:22:53 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytes(AbstractEpollStreamChannel.java:274)
21.01 12:22:53 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteSingle(AbstractEpollStreamChannel.java:483)
21.01 12:22:53 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:441)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
21.01 12:22:53 [Server] INFO at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:516)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:901)
21.01 12:22:53 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1396)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
21.01 12:22:53 [Server] INFO at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
21.01 12:22:53 [Server] INFO at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
21.01 12:22:53 [Server] INFO at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
21.01 12:22:53 [Server] INFO at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
21.01 12:22:53 [Server] INFO at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:1013)
21.01 12:22:53 [Server] INFO at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:248)
21.01 12:22:53 [Server] INFO at net.minecraft.class_2535.doSendPacket(class_2535.java:605)
21.01 12:22:53 [Server] INFO at net.minecraft.class_2535.mdcf6b1f$lambda$sendImmediately$rewrite$0$0(class_2535.java:582)
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
21.01 12:22:53 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
21.01 12:22:53 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
21.01 12:22:53 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:834)
21.01 12:22:53 [Server] INFO Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [randompatches.mixins.json:packetsizelimits.PacketInflaterMixin] from phase [DEFAULT] in config [randompatches.mixins.json] FAILED during APPLY
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
21.01 12:22:53 [Server] INFO ... 53 more
21.01 12:22:53 [Server] INFO Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("CONSTANT") on net/minecraft/class_2532::getMaxCompressedPacketSize with priority 1000 cannot inject into net/minecraft/class_2532::decode(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V merged by me.steinborn.krypton.mixin.network.pipeline.PacketInflaterMixin with priority 1000 [PREINJECT Applicator Phase -> randompatches.mixins.json:packetsizelimits.PacketInflaterMixin -> Prepare Injections ->  -> constant$bgd000$getMaxCompressedPacketSize(I)I -> Prepare]
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
21.01 12:22:53 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
21.01 12:22:53 [Server] INFO ... 53 more
21.01 12:22:53 [Disconnect] User com.mojang.authlib.GameProfile@67e845fd[id=c7e75acf-26ad-4b51-9ddc-bfea4250af02,name=Nozus44,properties={textures=[com.mojang.authlib.properties.Property@6fc5e907]},legacy=false] (/**.***.**.***:59752) has disconnected, reason: Disconnected`

**Comment by TheRandomLabs** [comment]
Does updating Krypton fix this issue?

**Comment by ivan-cavero** [comment]
Yes, it solves it, thank you very much.
