### ISSUE TITLE
[Fabric] Can't connect to server, 2.2.0

### ISSUE THREAD

**Issue by supersaiyansubtlety** [TheRandomLabs/RandomPatches#178]
Using `randompatches-2.2.0-fabric` I can't connect to my server.
 
The server+client both have default settings for testing. 

Everything was fine on 2.1.9

https://user-images.githubusercontent.com/618276/105643947-d25e0c80-5e47-11eb-89f0-fe73136a6224.mp4

I couldn't find anything useful in the logs, but here they are for both sides:

[client-latest.log](https://pastebin.com/Z8SsXT4p)

[server-latest.log](https://gitlab.com/-/snippets/2065669)

**Comment by supersaiyansubtlety** [comment]
filled out info properly now

**Comment by TheRandomLabs** [comment]
Does the issue persist without the mod?

**Comment by supersaiyansubtlety** [comment]
nope
at least not if I remove it from client+server, do you want me to try it one-sided?

**Comment by TheRandomLabs** [comment]
No, that's weird, because all I really did apart from removing a feature was adding a configuration option to disable logging fixed duplicate entity UUIDs...

**Comment by TheRandomLabs** [comment]
Does this still occur with 2.3.0?

**Comment by supersaiyansubtlety** [comment]
Looks like it's fixed!

**Comment by TheRandomLabs** [comment]
Sick!
