### ISSUE TITLE
Alt + F3 graph is broken with Randompatches

### ISSUE THREAD

**Issue by DVIcable** [TheRandomLabs/RandomPatches#179]
When RandomPatches is installed the Alt + F3 graph fails to work properly, instead displaying the normal f3 debug screen.

Without RandomPatches:
![2021-01-24_17 51 23](https://user-images.githubusercontent.com/76571917/105649580-03513800-5e6e-11eb-9c2c-8a6941535249.png)

With RandomPatches:
![2021-01-24_17 54 04](https://user-images.githubusercontent.com/76571917/105649619-2a0f6e80-5e6e-11eb-8e14-2af043df4f1d.png)

The Shift + F3 graph still works fine.

**Comment by TheRandomLabs** [comment]
Whoops, I made a typo.
