### ISSUE TITLE
Login Timeout no longer works

### ISSUE THREAD

**Issue by budgej** [TheRandomLabs/RandomPatches#18]
I am back to having login timeouts at exactly 30 seconds when connecting to a Forge server running 2770 and RandomPatches 1.10.0.0 with default configuration.

As best as I can tell, since Forge 2760 the networking code has been completely revamped and reorganized.  In my own attempts to modify Forge earlier this year I was able to reliably patch any version of Forge to have whatever time-out I needed in FMLNetworkHandler.  That file is now completely gone and is perhaps why RandomPatches is no longer affecting login timeout setting.  Can anyone confirm this?

Edit:  I have no idea what's going on, now I see FMLNetworkHandler in the Github source but not in my IntelliJ workspace.  I may be misunderstanding the patches.  However, I still am having the timeout after 30 sec.

**Comment by budgej** [comment]
Also still getting "player moved too quickly" messages and teleports.  These are the two worst features of Minecraft lol.  Attached log shows that I do have the mod installed.

[latest.log](https://pastebin.com/QM8mMTjx)

**Comment by TheRandomLabs** [comment]
And it was working fine before 2760?

**Comment by TheRandomLabs** [comment]
Can I see your `debug.log`? I don't see why the patch should suddenly stop working.

**Comment by TheRandomLabs** [comment]
RandomPatches 1.12.2-1.10.0.0 is working fine for me on Forge 14.23.5.2796. Can I have your `debug.log`?

**Comment by budgej** [comment]
I am sorry, it looks like my debug log from that session has been rotated out.  I have been able to connect within 3 seconds now so I have not been hitting the 30 second timeout, but here is a debug log from a more recent session.  (Too large for pastebin)

https://www.mediafire.com/file/hlql7x832yln77t/debug-5.log.gz/file

**Comment by TheRandomLabs** [comment]
Everything looks fine. You should remove Gotta Go Fast and you have a very old version of VanillaFix, but neither of those look to be causing the problem.

**Comment by budgej** [comment]
I appreciate your willingness to respond.  I'll close it for now.
