### ISSUE TITLE
Single-player world refuses to load when using beta versions 2.2.1 and 2.2.0 (fabric versions)

### ISSUE THREAD

**Issue by RangoMcRoony** [TheRandomLabs/RandomPatches#180]
My single player redstone ready world would get to 100% when launching the world and just perpetually stop at 100%. I experienced this with both beta versions. I'm currently using fabric loader version 0.11.1 on minecraft 1.16.5 (latest stable release at rime of writing). This is not an issue with RandomPatches version 2.1.9 (fabric) on the same fabric and minecraft versions. I'm not really a very technical person so i apologise if i cant provide enough details.

**Comment by TheRandomLabs** [comment]
Can you send me a log?

**Comment by justastranger** [comment]
Can confirm. Nothing illuminating shows up in the logs, though, to indicate why it's happening.

**Comment by RangoMcRoony** [comment]
@TheRandomLabs  I apologize for not sending a log, I've been really busy and preoccupied for personal reasons. When I get time I'll send it but it may take a while. Until then if anyone else is experiencing this issue they can pick up on this.

**Comment by TheRandomLabs** [comment]
Hey, no apologies needed. 😉 
Do you guys have AntiGhost installed? (#183)

**Comment by TheRandomLabs** [comment]
Open another issue if this still occurs in 2.3.0.

**Comment by RangoMcRoony** [comment]
Yep, I do have anti that y

**Comment by TheRandomLabs** [comment]
Yep, I fixed an incompatibility with AntiGhost.
