### ISSUE TITLE
Crash after adding Random Portals

### ISSUE THREAD

**Issue by CritFlaw** [TheRandomLabs/RandomPatches#19]
Forge version 2780
Minecraft 1.12.2
Random Patches version 1.11.0.0
Random Portals version 1.3.0.0

Crash log https://hastebin.com/cesofejuse.rb

**Comment by TheRandomLabs** [comment]
You need to update RandomPatches Integration.

**Comment by TheRandomLabs** [comment]
You actually have RandomPatches 1.12.2-1.10.0.0. RandomPatches-Integration 1.12.2-1.2.0.0 requires RandomPatches 1.12.2-1.11.0.0.
