### ISSUE TITLE
Anomaly bug w/ BetterEnd (forge) (server-crash)

### ISSUE THREAD

**Issue by Cixon** [TheRandomLabs/RandomPatches#190]
**Context:** Server lags like hell, then crashes.

### How to Replicate:
Wander around the end dimension city with these mods on a Forge-1.16.5-v36.0.7 server.
 
### Mods used:
[RandomPatches (forge) v2.2.1](https://www.curseforge.com/minecraft/mc-mods/randompatches-forge/files/3182722)
[BetterEnd (forge) v1.4.1](https://www.curseforge.com/minecraft/mc-mods/betterend-forge-port/files/3185939)
[ClothConfigAPI v4.1.3](https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge/files/3155284)

### LOGS:
[latest.log](https://github.com/TheRandomLabs/RandomPatches/files/5901128/latest.log) **Line 1456**
[debug.log](https://github.com/TheRandomLabs/RandomPatches/files/5901142/debug.log)

**Comment by TheRandomLabs** [comment]
Hmm, and you're certain this is caused by my mod? I've just run around in singleplayer in an end city and not had this issue; maybe it has to be on a server?

**Comment by Cixon** [comment]
> 
> 
> Hmm, and you're certain this is caused by my mod? I've just run around in singleplayer in an end city and not had this issue; maybe it has to be on a server?

It happened on the server. I'm certain it's randompatches because of the log spam but I could be wrong.

**Comment by TheRandomLabs** [comment]
Can you find a way to consistently reproduce this? If so, does it still occur when the duplicate entity UUID fix is disabled?

**Comment by Cixon** [comment]
I disabled the UUID fix and this didn't seem to have solved the issue. Seems to be something with BetterEnd.
My apologies.

**Comment by TheRandomLabs** [comment]
All good! 😄
