### ISSUE TITLE
Error in console on startup - java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by ProsperCraft** [TheRandomLabs/RandomPatches#2]
https://gist.github.com/ProsperCraft/3b4bce26a74a83cbd901cb48d8fb0642

**Comment by ProsperCraft** [comment]
It was with this pack, on the server console that it happened.

https://minecraft.curseforge.com/projects/towncraft

**Comment by TheRandomLabs** [comment]
Thanks for reporting this. The mod's not patching a specific method for some reason.

**Comment by TheRandomLabs** [comment]
I ran a server with that same modpack, and I didn't get this error. Could you provide some more details?

**Comment by TheRandomLabs** [comment]
Fixed in 1.12.2-1.0.1.0.
