### ISSUE TITLE
RandomPatches breaks ExtraUtils Golden Lasso

### ISSUE THREAD

**Issue by NielsPilgaard** [TheRandomLabs/RandomPatches#20]
Original issue: https://github.com/NillerMedDild/Enigmatica2Expert/issues/460

Hello o/

It appears RandomPatches makes Golden Lassos unable to move entities correctly, please see the original issue for a very thorough explaination. The user DedN00b was kind enough to test the issue, and he discovered that removing RandomPatches, or downgrading to version `1.8.0.0` fixed the issue. 

Could this be caused by implementing the fix for MC-2025.?

### Versions
- Minecraft 1.12.2
- Forge 1.12.2-14.23.5.2768
- RandomPatches, all versions above 1.12.2-1.8.0.0

**Comment by TheRandomLabs** [comment]
Thanks for reporting this. Yes, this was caused by the MC-2025 fix. I can fix it by storing the bounding box as relative instead of absolute.
