### ISSUE TITLE
ModifyConstant Conflicts With XL Packets Fabric

### ISSUE THREAD

**Issue by CoolMineman** [TheRandomLabs/RandomPatches#200]
https://github.com/TheRandomLabs/RandomPatches/blob/1.16-fabric/src/main/java/com/therandomlabs/randompatches/mixin/packetsizelimits/PacketInflaterMixin.java
https://github.com/Tfarcenim/XLPacketsFabric/blob/master/src/main/java/tfar/xlpackets/mixin/PacketInflaterMixin.java
https://github.com/TheRandomLabs/RandomPatches/blob/1.16-fabric/src/main/java/com/therandomlabs/randompatches/mixin/packetsizelimits/PacketByteBufMixin.java
https://github.com/Tfarcenim/XLPacketsFabric/blob/master/src/main/java/tfar/xlpackets/mixin/PacketByteBufMixin.java
Causes CoolMineman/BitsAndChisels#18

**Comment by TheRandomLabs** [comment]
RandomPatches makes XL Packets redundant. However, I'll prevent the crash from occurring.
