### ISSUE TITLE
Feature request: Make Vanilla Defaults Easier

### ISSUE THREAD

**Issue by Boobies** [TheRandomLabs/RandomPatches#201]
In a couple of cases, it's not obvious how to simulate vanilla behaviour:

- MC-91206 has been marked as "works as intended" and the RandomPatches "fix" breaks various redstone contraptions that rely on boats sinking. The readme states that RandomPatches sets the buoyancy to a positive value but it's not clear what the original value expected by vanilla is. It would be nice if it was mentioned in the config menu or there was some option not to fix that "bug".
- MC-100044 has been marked as "worked as intented" and the configuration for it consists of a text box. It's not obvious what to put inside of it in order to prevent this bug from being "fixed" and to restore vanilla behavior. RandomPatches provides the following text: `REQUIRE_SAME_PLAYER_AND_TEXTURE_URL`.

**Comment by TheRandomLabs** [comment]
You can look at the configuration on disk for more detailed comments that I couldn't fit into the tooltips. It's not obvious, but you can remove that text for it to suggest all possible values.
(The values you want are `-0.0007` and `DISABLED`.)

**Comment by TheRandomLabs** [comment]
I'll see if I can fit `-0.0007` into the in-game tooltip.
