### ISSUE TITLE
[1.16.5] Randompatches v2.4.4 & Performant v3.3.0m

### ISSUE THREAD

**Issue by Cixon** [TheRandomLabs/RandomPatches#204]
**Context:** I use random-patches forge with performant and it's a bit of a eyesore and a bit concerning seeing an error message considering both mods use player-timeout functions. I love both mods and getting rid of 1 would ruin a lot of things.

Though it's just a minor issue, i'd love a way to get around this server log message when I boot up the server or perhaps a way to disable modifying the player timeout for random-patches cause I'd rather use Performant's method considering its purpose is to increase server performance and lower ping. 

**Here's Error Message:**
>.... [23:45:51] [Server thread/WARN] [mixin/]: @ModifyConstant conflict. Skipping performant.mixins.json:connection.ServerPlayNetHandlerMixin->@ModifyConstant::playTimeout(J)J with priority 1000, already redirected by randompatches.mixins.json:timeouts.ServerPlayNetHandlerKeepAliveMixin->@ModifyConstant::getKeepAlivePacketInterval(J)J with priority 1000

**Comment by TheRandomLabs** [comment]
I'd prefer to keep my version, as I take into account both the timeout and packet interval. However, if you absolutely insist on using Performant's version, you can add `"ServerPlayNetHandlerKeepAlive"` to the mixin blacklist.
