### ISSUE TITLE
Possible server tick lag buildup with mob loading

### ISSUE THREAD

**Issue by Bidgam** [TheRandomLabs/RandomPatches#207]
1.16.5 with Forge 36.0.15 and RandomPatch 2.4.0.

Not sure this involves the mod, but I should bring it up. I fly around for maybe 5 minutes (fairly fast back and forth over a thousand blocks or so) and this tick lag starts. It won't stop either until I restart the server (even if I myself stop and just let my character idle).

Log: https://imgur.com/a/jPCr99J

I noticed randompatches gets quite frequent in updating mobs (naturally due to me moving through terrain).

A Spark report also shows a lot of entity activity with 60% entity use at times.

Could randompatches be stressing out the entity system somehow?

I should also note that this tick lag eventually happens even if I'm not flying around and trying to be conservative with my activities. Eventually it'll start at one point or another, even if it's a few hours into play.

Thanks for taking a look.

**Comment by TheRandomLabs** [comment]
Can you check if disabling the duplicate entity UUID fix resolves this issue?

**Comment by Bidgam** [comment]
Sorry, I'm not sure how to do that. In a config file?

**Comment by TheRandomLabs** [comment]
Yep, it's in the configuration.

**Comment by Bidgam** [comment]
Changed the setting to False.

It didn't seem to do anything noticeable for the lag at least. I run back and forth over a thousand blocks. Not at first as you can but soon after it just 'gets going' and I just sit there at that point watching this continue infinitum:

https://imgur.com/a/WpVeIiU

**Comment by TheRandomLabs** [comment]
Just as another test, can you try removing my mod and seeing if the issue persists?

**Comment by Bidgam** [comment]
Will do.

To note, I just completed a few additional tests with it installed before
seeing your message. I flew around back and forth in both the Nether and
End, as well as using Waystones to bounce back and forth between those two
dimensions, avoiding the Overworld entirely.

I did this for at least 20 minutes in each dimension.

I not only didn't get any tick lag but I also didn't get any RandomPatches
updates.

This may just be a coincidence, but wanted to let you know. Does
RandomPatches not function in these other dimensions, or is it on a
different level?

**Comment by Bidgam** [comment]
Unfortunately I can't remove it now, it breaks my login: 

https://imgur.com/a/6CQ15vL

Any way around that (hopefully ;))?

**Comment by TheRandomLabs** [comment]
It shouldn't differentiate between the dimensions.
I suppose you could try using XL Packets to replicate the packet size limit functionality. 😄

**Comment by Bidgam** [comment]
1. Well, for whatever reason it just didn't come up, so I dunno why. Different mobs that don't need ID changes?

2. I'm not sure I understand. I uninstalled the mod, it should work without the mod installed but it gave the above error. What's wrong?

**Comment by Bidgam** [comment]
Unfortunately removing the mod didn't resolve the issue, in fact I think the mod actually helped to a degree by not causing "moved too quickly" messages to come up nearly as often, but the tick lag still shows:

https://imgur.com/a/phNICBX

Sorry for the bother, but unless your mod keeps things around somehow that may still affect it, my issue isn't with your mod.

**Comment by Bidgam** [comment]
Do I need to restore a backup of my world since I briefly removed your mod, or is there nothing world altering I should worry about?

**Comment by TheRandomLabs** [comment]
You don't need to restore a backup. 😄 
I hope you figure out your problem!
