### ISSUE TITLE
 1.12.2-1.13.0.0 crashes dedicated server Forge 1.12.2 build 2811

### ISSUE THREAD

**Issue by kreezxil** [TheRandomLabs/RandomPatches#23]
crash report:
http://paste.ubuntu.com/p/Z38DTX7g8D/

fml server latest:
http://paste.ubuntu.com/p/Vmzv4t9W5N/

**Comment by TheRandomLabs** [comment]
I *knew* there'd be issues with that build. Thanks for reporting!
