### ISSUE TITLE
AE2 not worked

### ISSUE THREAD

**Issue by ghost** [TheRandomLabs/RandomPatches#24]
After the last update, crash from refined storage. I have ceases to work ae2 me system after a certain time.

**Comment by TheRandomLabs** [comment]
Thanks for testing the beta! Could I have a crash report?

**Comment by ghost** [comment]
I'm sorry, but any mistakes fiction. The drive just stops working after a while

**Comment by ghost** [comment]
and i have one problems with skull
https://pastebin.com/Y3yWSKpj

**Comment by TheRandomLabs** [comment]
That crash was fixed in 1.12.2-1.13.0.1. Unfortunately, I'm not well acquainted with Refined Storage, but I'll try to investigate it soon.

**Comment by ghost** [comment]
The problem I encountered was not in Refined Storage.
https://minecraft-ru.gamepedia.com/Applied_Energistics_2/%D0%9C%D0%AD_%D0%BF%D1%80%D0%B8%D0%B2%D0%BE%D0%B4
In 1.12.2-1.13.0.1 i have problem with this block.
It stops working after a while. But if you pull the storage card out of it and insert it, it will start to work, but not for long.

**Comment by TheRandomLabs** [comment]
Could I have debug.log?

**Comment by ghost** [comment]
I tried to catch this problem but there is nothing in the logs. The feeling that this unit just ceases to generate ticks.

**Comment by TheRandomLabs** [comment]
A `debug.log` would be nice anyway. Also, does this issue persist upon disabling `misc.skullStackingFix` in the configuration?

**Comment by ghost** [comment]
hmm...I will try to disable

**Comment by svandajan** [comment]
I seem to have the same problem (RefinedStorage Importer is importing content of chest where (I suspect) is also Player's Head):
[https://pastebin.com/j6Bqp3QK](https://pastebin.com/j6Bqp3QK)
`Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	**at com.therandomlabs.randompatches.patch.NBTTagCompoundPatch.getTextures(NBTTagCompoundPatch.java:135)
	at com.therandomlabs.randompatches.patch.NBTTagCompoundPatch.areTagMapsEqual(NBTTagCompoundPatch.java:126)**
	(...)`

**Comment by TheRandomLabs** [comment]
Thank you for the stack trace! Now I can fix this.
