### ISSUE TITLE
re:mixin,pl:accesstransformer Mod Loading has failed

### ISSUE THREAD

**Issue by Macleykun** [TheRandomLabs/RandomPatches#250]
I'm getting this error. It seems to be related to randompatches, but when i only run the conflicting mods (that errors gives) with randompatches. Everything weirdly enough still work
[crash-2021-10-30_10.38.55-fml.txt](https://github.com/TheRandomLabs/RandomPatches/files/7446112/crash-2021-10-30_10.38.55-fml.txt)
s.
What you think?

**Comment by RVOtakuMike** [comment]
I am getting this too. Heres my logs aswell. 
[2021-11-02-1.log](https://github.com/TheRandomLabs/RandomPatches/files/7464343/2021-11-02-1.log)
[crash-2021-11-02_18.19.39-fml.txt](https://github.com/TheRandomLabs/RandomPatches/files/7464344/crash-2021-11-02_18.19.39-fml.txt)
[debug-1.log](https://github.com/TheRandomLabs/RandomPatches/files/7464345/debug-1.log)

**Comment by mosharky** [comment]
getting this too

**Comment by Macleykun** [comment]
> getting this too

give the crash log, that'll help atleast more

**Comment by mosharky** [comment]
after looking deeper into it, this may not be the same exact crash: https://pastebin.com/WLEGx3Xb

**Comment by Macleykun** [comment]
> after looking deeper into it, this may not be the same exact crash: https://pastebin.com/WLEGx3Xb

try disabeling some mods, until the error doesn't happen, renable some back on until the error comes, repeat until you are left with the mod that gives issues.

**Comment by mosharky** [comment]
RandomPatches is making a huge amount of mods fail to load. I don't have the time to test every single one, but thus far Create, Ender Storage, and Chicken Chunks have caused a mod loading error with RandomPatches installed

**Comment by Seikm** [comment]
> RandomPatches is making a huge amount of mods fail to load. I don't have the time to test every single one, but thus far Create, Ender Storage, and Chicken Chunks have caused a mod loading error with RandomPatches installed

I'm having this exact same error, with the exact same mods

**Comment by Seikm** [comment]
> > RandomPatches is making a huge amount of mods fail to load. I don't have the time to test every single one, but thus far Create, Ender Storage, and Chicken Chunks have caused a mod loading error with RandomPatches installed
> 
> I'm having this exact same error, with the exact same mods

I just fixed the error putting this in the mixin blacklist.
`mixin_blacklist = ["ServerPlayNetHandlerKeepAlive"]`

**Comment by Macleykun** [comment]
Can you guys try this? https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility
I think it solved it?
