### ISSUE TITLE
Compatibility Issue with Slash Blade

### ISSUE THREAD

**Issue by kreezxil** [TheRandomLabs/RandomPatches#27]
https://github.com/kreezxil/World-of-Dragons/issues/79

A player of my pack is reported an issue that crashes them when using Slash Blade, the first mod mentioned in the stack trace is RandomPatches.

server crash report: https://pastebin.com/uWD0YQct

**Comment by TheRandomLabs** [comment]
Reopen this if it's not fixed in 1.14.1.0.

**Comment by kreezxil** [comment]
Yep not fixed, some 3 mods in the stack trace too.

server side crash report: https://pastebin.com/MnbS9hSG
