### ISSUE TITLE
Yep not fixed, same 3 mods in the stack trace too.

### ISSUE THREAD

**Issue by kreezxil** [TheRandomLabs/RandomPatches#29]
Yep not fixed, some 3 mods in the stack trace too.

server side crash report: https://pastebin.com/MnbS9hSG

_Originally posted by @kreezxil in https://github.com/TheRandomLabs/RandomPatches/issues/27#issuecomment-471054154_

**Comment by TheRandomLabs** [comment]
If you haven't already, you can disable the skull stacking fix for now.

**Comment by TheRandomLabs** [comment]
Alright, this time it should actually be fixed. I think.
