### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Xiaminou** [TheRandomLabs/RandomPatches#3]
[crash-2018-04-26_21.12.43-server.txt](https://github.com/TheRandomLabs/RandomPatches/files/1952671/crash-2018-04-26_21.12.43-server.txt)

Minecraft: 1.12.2
Forge: 2673

**Comment by Dalethium** [comment]
[Crash Log](https://pastebin.com/Jtnru54C) Confirmed.

**Comment by TheRandomLabs** [comment]
Sorry about that. I forgot to load the coremod on the server as well while testing.
