### ISSUE TITLE
Not Sure...

### ISSUE THREAD

**Issue by O13SC3N3** [TheRandomLabs/RandomPatches#30]
Forge 2768
RandomPatches 1.12.2-1.15.0.0 
and
RandomPatches 1.12.2-1.14.1.1

https://pastebin.com/raw/1BB1ceJS with Just Enough Ids
https://pastebin.com/raw/apEEjWb6 when Just Enough Ids disabeled, don't recall this in the console before.

**Comment by TheRandomLabs** [comment]
ReBind is replacing the Toggle Narrator keybind before RandomPatches. I'll just disable the Toggle Narrator keybind if ReBind is installed.
