### ISSUE TITLE
Ticking player server and client crash

### ISSUE THREAD

**Issue by Dimentive** [TheRandomLabs/RandomPatches#31]
**Crash log:** https://pastebin.com/raw/SyTByGii
**RandomPatches version:** 1.15.0.0
**Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2), version 1.62, for Minecraft 1.12.2

My local server that I play on with a friend crashed, and my friend’s client also crashed. They seemed to be similar crash logs. My client did not crash, however.

When this crash happened, my friend was placing a player head of him on the wall. Every time he tries to join the server now, he gets the very same crash, although I can still join the server. We had to restore to a backup of the world. It seems as though placing a vanilla head of his skin might have corrupted the world.

**Comment by TheRandomLabs** [comment]
Already fixed in 1.15.0.2.

**Comment by Dimentive** [comment]
Oh, all right. I looked through the two newer versions, but I totally missed that this bug had been fixed in the latest version, which I really shouldn’t have considering it’s the only thing in the changelog.

Thank you. I’ll be updating the mod to version 1.15.0.2 right away! 👍
