### ISSUE TITLE
Icon Config

### ISSUE THREAD

**Issue by NielsPilgaard** [TheRandomLabs/RandomPatches#34]
Hey o/

I'm having some trouble getting the Window Icon configuration to work. May I ask which image format it accepts?

**Comment by TheRandomLabs** [comment]
A png file should be fine, but if that doesn't work then I'll do some
testing.

**Comment by TheRandomLabs** [comment]
It accepts PNG files. `client.window.icon16` and `client.window.icon32` should point to a PNG file path relative to the Minecraft instance directory.

**Comment by NielsPilgaard** [comment]
Ah! I was using the path relative to the resources folder, thanks :)
