### ISSUE TITLE
Error in Console with SpongeForge

### ISSUE THREAD

**Issue by TheRealDadbeard** [TheRandomLabs/RandomPatches#38]
https://hastebin.com/ipefeseyim.rb

SpongeForge spongeforge-1.12.2-2838-7.1.7-RC3817
Forge forge-1.12.2-14.23.5.2838-universal
RandomPatches 1.12.2-1.16.3.0

Error pops up in the console when someone is connecting but nothing else seem to happen.

**Comment by TheRandomLabs** [comment]
I'll just disable that patch when SpongeForge is installed, but it
shouldn't be causing any issues.

**Comment by TheRealDadbeard** [comment]
Do you know which patch it is? I can't really decipher it from that error message,

**Comment by TheRandomLabs** [comment]
The max packet size patch.

**Comment by TheRealDadbeard** [comment]
Okay thank you very much!

**Comment by TheRealDadbeard** [comment]
Is it this? Can't find any other option which comes close to anything max packet size related B:patchNetHandlerPlayServer

**Comment by TheRandomLabs** [comment]
It's `misc.patchPacketSizeLimit`, but I'm about to release a fix anyway.
