### ISSUE TITLE
Is this stacktrace helpful at all? NPE - objectweb.asm.tree.InsnList.insert

### ISSUE THREAD

**Issue by ProsperCraft** [TheRandomLabs/RandomPatches#39]
https://gist.github.com/ProsperCraft/7927d8f5a505c46aa8b81faf78d23cbe

**Comment by TheRandomLabs** [comment]
That just means RandomPatches is conflicting with another mod. It shouldn't cause any issues, but can I have the mod list anyway?

**Comment by ProsperCraft** [comment]
https://www.curseforge.com/minecraft/modpacks/drtardis-2-new-adventures
