### ISSUE TITLE
game crash after last game update (STONE BLOCK 2)

### ISSUE THREAD

**Issue by horse142029** [TheRandomLabs/RandomPatches#42]
[crash-2019-07-08_21.06.49-server.txt](https://github.com/TheRandomLabs/RandomPatches/files/3368754/crash-2019-07-08_21.06.49-server.txt)

**Comment by horse142029** [comment]
Please help me this mod crash 3 times on me

**Comment by TheRandomLabs** [comment]
This looks like a problem with MineTogether. RandomPatches has nothing to do with this.

**Comment by TheRandomLabs** [comment]
FTBTeam/FTB-Presents-Stoneblock-2#560

**Comment by horse142029** [comment]
> [FTBTeam/FTB-Presents-Stoneblock-2#560](https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/560)

and what can i do now

**Comment by TheRandomLabs** [comment]
Try deleting MineTogether.
