### ISSUE TITLE
[Question] About It's the little things mod

### ISSUE THREAD

**Issue by xJon** [TheRandomLabs/RandomPatches#43]
Is it possible to use RandomPatches' configurable window title/icon option even when Itlt is installed? I'd want to use this mod's implementation whilst still having Itlt for other purposes.
Thanks for the help!

**Comment by TheRandomLabs** [comment]
At the moment, RandomPatches disables its own window title/icon option when It's the little things is installed, but I can remove that restriction. Out of curiosity, which features of It's the little things are you using?

**Comment by xJon** [comment]
`AddDedicatedServer` as a featured server that's shipped with a pack.
Thank you for the quick and helpful response!

**Comment by xJon** [comment]
Thank you so much. You might also want to edit the CurseForge mod description.

**Comment by TheRandomLabs** [comment]
Thanks for reminding me!
