### ISSUE TITLE
[1.14.3] Server crash -NPE minecraft.entity.Entity.func_184191_r(Entity.java:1913) ~[?:?] {pl:accesstransformer:B,xf:fml:randompatches:RandomPatches

### ISSUE THREAD

**Issue by ProsperCraft** [TheRandomLabs/RandomPatches#44]
https://gist.github.com/ProsperCraft/50d12b6901f0fe5aefc0a7663e3e5d97

This may not be related to your mod, we have only had it once, the player on the server said he had the insulated III potion effect.

randompatches-1.14.3-1.17.2.1
forge-1.14.3-27.0.60

Modpack- https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by TheRandomLabs** [comment]
As far as I know, this doesn't have anything to do with my mod.
