### ISSUE TITLE
[1.14.4] Update please, login timeouts are a thing of the past with RandomPatches :)

### ISSUE THREAD

**Issue by ProsperCraft** [TheRandomLabs/RandomPatches#45]
perties.Property@4f3ab2c1]},legacy=false] (/73.3.64.81:60978) lost connection: Took too long to log in

Sadface due to slow computer 😞

**Comment by TheRandomLabs** [comment]
Crap, alright.

**Comment by TheRandomLabs** [comment]
It's still working fine for me. Just to clarify, was RandomPatches installed on the server? If so, did the server wait more than 900 seconds before disconnecting the client?

**Comment by ProsperCraft** [comment]
Sorry I was not clear, please update to 1.14.4  we are no longer testing 1.14.3.

If I remember correctly, Randompatches has a hard dep on 1.14.3 so we could not load it.

**Comment by TheRandomLabs** [comment]
I didn't realize it wouldn't load on 1.14.4.
