### ISSUE TITLE
[1.14.4] Minecraft Window icon and titel 

### ISSUE THREAD

**Issue by Sunekaer** [TheRandomLabs/RandomPatches#46]
Hi 
As you can see on the image below, the title of the minecraft window has changed to "RandomPatches" and the icon is missing
![image](https://user-images.githubusercontent.com/18720460/62230662-949f3580-b3c2-11e9-8782-0d96f262baa7.png)

Tried on forge 28.0.24 and .27
randompatches-1.14.4-1.17.3.0.jar

**Comment by jakey1995abc** [comment]
My modpack is having the exact same issue using latest forge version for 1.14.4. Is this issue occuring on any other mod / minecraft versions?

**Comment by TheRandomLabs** [comment]
This is because I forgot to disable a testing option. Sorry!

**Comment by ProsperCraft** [comment]
oh, I thought it was due to not having a config where we could edit those.

**Comment by TheRandomLabs** [comment]
Nah, but I'll try to have the config done by tomorrow.
