### ISSUE TITLE
[1.14.4] Incompatibility With RFTools Power

### ISSUE THREAD

**Issue by TheLimePixel** [TheRandomLabs/RandomPatches#51]
In the latest forge versions many changes have been done, most notably to render and tick events. On forge 28.0.45 when trying to load up RFTools Power 1.2.3 with RandomPatches 17.3.1 (or 18.0.0) a crash occurs. The crash log points towards RFTools Power being the cause, but seeing the crash doesn't occur without RandomPatches I presume it's caused due to a patch to the method used.
https://pastebin.com/Phk674Dw

**Comment by TheRandomLabs** [comment]
I'm able to load RandomPatches with RFTools Base and RFTools Power without any issues. Additionally, RandomPatches doesn't touch the two methods in question. Could I have `debug.log`?

**Comment by TheLimePixel** [comment]
Strange, well I'm on vacation rn, so I can't really get any logs currently, so I guess I'm gonna close this for now.

**Comment by TheLimePixel** [comment]
Strange, well I'm on vacation rn, so I can't really get any logs currently, so I guess I'm gonna close this for now.

**Comment by TheRandomLabs** [comment]
Never mind, I've managed to reproduce it.

**Comment by TheRandomLabs** [comment]
Never mind, false alarm.
