### ISSUE TITLE
[1.14.4] Server crash ParsingException: Invalid character 's' after key

### ISSUE THREAD

**Issue by ProsperCraft** [TheRandomLabs/RandomPatches#52]
https://gist.github.com/ProsperCraft/79efa1be970a65d0c1c7834823076c02

I have not changed the config, and after it happened the first time I wiped the config, then it happened again.

Here is the useless crash report-
https://paste.fedoraproject.org/paste/bVOhcv7RXw0DRdGzbRmn7g

randompatches-1.14.4-1.18.1.0
forge-1.14.4-28.0.45

**Comment by TheRandomLabs** [comment]
Strange, I'm not able to reproduce this issue. However, I'll change it so that RandomPatches just recreates the configuration instead of crashing if there's a problem.

**Comment by ProsperCraft** [comment]
I had it happen a third time, so I just added a comment to the line that is missing the first few characters including the comment.

**Comment by TheRandomLabs** [comment]
That is very strange. I probably screwed something up, but I can't reproduce it.
