### ISSUE TITLE
Question regarding crash when logging out of server

### ISSUE THREAD

**Issue by xJon** [TheRandomLabs/RandomPatches#53]
Do you think there is any chance the crash is caused by RandomPatches?
https://paste.dimdev.org/ecuvipafix.mccrash
I'm asking because I know the mod handles things related to `NetHandlerPlayClient.handleTimeUpdate`.

It doesn't seem to have a lasting effect, and I'm using VanillaFix so it basically doesn't have any effect, but I still can't track down the cause.
Reproducing it is difficult, because it happens at random times.

Thanks for any feedback!

**Comment by TheRandomLabs** [comment]
No, this shouldn't have anything to do with RandomPatches.

**Comment by xJon** [comment]
Do you have a clue regarding what could be a possible cause, anyway?

**Comment by TheRandomLabs** [comment]
The client is trying to handle a time update packet while not in a world. The game tries to access the current world, which is `null`, so a `NullPointerException` is thrown. I don't know what could be causing this.

**Comment by xJon** [comment]
Thank you!
