### ISSUE TITLE
Smooth eye level implementation is incompatible with BetterPortals

### ISSUE THREAD

**Issue by Johni0702** [TheRandomLabs/RandomPatches#54]
https://github.com/Johni0702/BetterPortals/issues/259

BetterPortals (MC 1.12.2) maintains multiple `EntityRenderer` instances in order to have multiple worlds loaded at the same time.
The current implementation of the smooth-eye-level-change patch assumes there to only be a single EntityRenderer by keeping the previous eye level vales in static fields:
https://github.com/TheRandomLabs/RandomPatches/blob/e21150852d8b05c114cabbcfb3bd5be7b3734a1b/src/main/java/com/therandomlabs/randompatches/patch/client/EntityRendererPatch.java#L19-L20

The simplest (in terms of ASM) and at the same time most idiomatic solution would be to change those to be instance fields, patch a single `EyeHeightHandler` field into the `EntityRenderer` class and then use it instead of static methods.

**Comment by OverInfrared** [comment]
You are very intelligent. But I am glad I could help!

**Comment by TheRandomLabs** [comment]
Fixed by patching an `EyeHeightHandler` field into the `EntityRenderer` class.
