### ISSUE TITLE
Crash on loading world when used with randomportals

### ISSUE THREAD

**Issue by GMTrist** [TheRandomLabs/RandomPatches#55]
[crash-2019-08-21_12.25.30-server.txt](https://github.com/TheRandomLabs/RandomPatches/files/3524898/crash-2019-08-21_12.25.30-server.txt)

[1.12.2] tried having just randomportals and randompatches on a fresh instance but keeps crashing when loading a world

**Comment by TheRandomLabs** [comment]
You'll have to update your Forge version.

**Comment by GMTrist** [comment]
thank you very much, I was using the recommended one for 1.12.2, but switching to the latest one worked
