### ISSUE TITLE
[Feature Request] [1.12] Fix desync issue MC-5694

### ISSUE THREAD

**Issue by NightMean** [TheRandomLabs/RandomPatches#58]
Hey, I run a server with ~250 mods and I've noticed that every pickaxe or anything that's fast will result with desync, upon googling I've found that it's a vanilla issue and I've found only 1 mod which apparently fixes that but it doesn't work properly as it's throwing errors. I was thinking if it's possible for you to port this fix to your mod.

**Comment by TheRandomLabs** [comment]
Is Carpet Mod the mod that you found? If so, can I see the errors that are being thrown?

**Comment by NightMean** [comment]
No it's not, the carpet mod doesn't support forge but the one I found does. It crashes minecraft if all fixes are enabled (something with Thermal Dynamics). It does have quite a few issues with compatibility with other mods. But if you enable only the MC-5694 fix it'll launch but vanilla fix will show a crash once you load a world (idk if you wan't to see it as it's not the carpet mod but here you go) https://paste.dimdev.org/umehuvubew.mccrash

**Comment by TheRandomLabs** [comment]
Sorry for the late response! A server-sided fix taken from Carpet Mod will be in 1.12.2-1.19.0.0.
