### ISSUE TITLE
[1.14.4] Crash on load - After changing speed config.

### ISSUE THREAD

**Issue by ProsperCraft** [TheRandomLabs/RandomPatches#60]
net.minecraft.crash.ReportedException: Failed to deserialize configuration property speedLimits.maxPlayerSpeed

Log-
https://gist.githubusercontent.com/ProsperCraft/2699f48ec56367310e7edfd954ada0ed/raw/db97cf6dc255677baf9e3c3401b63c2fc30378fc/gistfile1.txt

![2019-09-17_08 44 19](https://user-images.githubusercontent.com/4427684/65052384-aa8f9800-d927-11e9-93fa-a1c29e339e95.png)

Config-
https://gist.github.com/ProsperCraft/19a9b1ac2de7ff4a00208abefe7bd92d

**Comment by TheRandomLabs** [comment]
This was because you forgot the `.0` at the end. 1.14.4-1.18.2.1 will convert the integer to a double correctly.
