### ISSUE TITLE
Crash when setting Logo

### ISSUE THREAD

**Issue by NielsPilgaard** [TheRandomLabs/RandomPatches#64]
Hello o/

I crashed while trying to set the Minecraft logo to a custom one - I'm guessing the png I tried this time was corrupt in some way, cause other pngs work. Anywho, I figured I would report it.

Java log, was put in my instance root after the crash:
https://gist.github.com/NillerMedDild/ab2c42273a72f803db21082ddc47c30e

Png I used for easier testing:
![icon2](https://user-images.githubusercontent.com/21295394/66260129-a7ffc000-e7ba-11e9-8dea-56f4096968e5.png)

### Version
- randompatches-1.14.4-1.19.0.0

**Comment by TheRandomLabs** [comment]
RandomPatches should correctly resize the icon now.

**Comment by NielsPilgaard** [comment]
Thanks!

**Comment by NielsPilgaard** [comment]
The crash is gone, but the resizing doesn't look quite right. Below is what the icon for the above image, with a transparent background, looks like.
![billede](https://user-images.githubusercontent.com/21295394/66264521-34d06b00-e807-11e9-9aaa-f1b1af656393.png)

**Comment by TheRandomLabs** [comment]
I'm not sure why, but when the background is made transparent, the icon appears correctly. I'll investigate this soon.
Logo with transparent background:
![image](https://user-images.githubusercontent.com/16755704/66268043-bd412100-e884-11e9-8ea9-4c127e695130.png)
Taskbar icon:
![image](https://user-images.githubusercontent.com/16755704/66268041-b74b4000-e884-11e9-9a9f-641cb3027bb5.png)
#65

**Comment by NielsPilgaard** [comment]
The image I had trouble with already has a transparent background, I'm guessing that was lost when downloaded. I'm curious, how did you make it transparent? Maybe it's my method that's at fault.

**Comment by NielsPilgaard** [comment]
I believe my method messed up the picture, I just tried with a version I made transparent with photoshop, and that seems to work out of the box. Thanks for your help again.
