### ISSUE TITLE
Window icon displays strangely when background is not transparent

### ISSUE THREAD

**Issue by TheRandomLabs** [TheRandomLabs/RandomPatches#65]
Logo with opaque background:
![image](https://user-images.githubusercontent.com/21295394/66260129-a7ffc000-e7ba-11e9-8dea-56f4096968e5.png)
Taskbar icon with opaque background:
![image](https://user-images.githubusercontent.com/21295394/66264521-34d06b00-e807-11e9-9aaa-f1b1af656393.png)
Logo with transparent background:
![image](https://user-images.githubusercontent.com/16755704/66268043-bd412100-e884-11e9-8ea9-4c127e695130.png)
Taskbar icon with transparent background:
![image](https://user-images.githubusercontent.com/16755704/66268041-b74b4000-e884-11e9-9a9f-641cb3027bb5.png)

**Comment by kreezxil** [comment]
i got this strange rendering in 1.14.4-1.19.11 thanks to this information, I will now add a transparent layer that won't be visible but I think will solve the issue.

Yes that worked! I used GIMP to add a transparency layer to my icons. I use all the space on a set of icons in some instances. Simply adding the transparency to the image and that was enough to make it no longer scrambled.

**Comment by TheRandomLabs** [comment]
Almost a year late, it turns out I just needed to specify four channels.

**Comment by kreezxil** [comment]
nice
