### ISSUE TITLE
[1.14.4] randompatches-1.14.4-1.19.1.0.jar blocks players from logging in to a dedicated server.

### ISSUE THREAD

**Issue by ProsperCraft** [TheRandomLabs/RandomPatches#67]
Unable to log in to my dedicated server after updating to randompatches-1.14.4-1.19.1.0.jar

wiped the world-  still could not log in

disabled many other mods- still could not log in

wiped the world and disabled random patches - able to log in.

**Comment by TheRandomLabs** [comment]
My bad, I forgot to load the config on the server.
