### ISSUE TITLE
Cubic Chunks incompatibility with RP

### ISSUE THREAD

**Issue by jonthemoron** [TheRandomLabs/RandomPatches#68]
When using Cubic Chunks, the character gets locked into place once you reach a height corresponding to the set vertical chunk loading setting. This problem is gone after removing Random Patches, and there is nothing stated in the latest.log or debug.log.

**Comment by TheRandomLabs** [comment]
I cannot reproduce this with RandomPatches 1.12.2-1.20.1.0. Reopen this if this is still an issue. :)
