### ISSUE TITLE
[1.12.2 - Suggestion] Observer 'activation on place' Fix

### ISSUE THREAD

**Issue by ghost** [TheRandomLabs/RandomPatches#70]
When observers were introduced in 1.11 they had a 'functionality' where they would immediately pulse when being placed, as described by "[MC-109832]" and other similar duplicates, this behavior persisted through 1.12.2 as well and was eventually considered a glitch instead of working as intended because of how it made 'slimestone' machines, clocks and other various contraptions more difficult to work with. Now in 1.13+ the observer does not immediately pulse when being placed. If possible, the addition of a patch for 1.12.2 to make observers not pulse when being placed would be a nice addition and change.

**Comment by TheRandomLabs** [comment]
A bit late, but this will be in 1.12.2-1.21.0.0. :)
