### ISSUE TITLE
SpongeForge incompatibility not fixed

### ISSUE THREAD

**Issue by LokeYourC3PH** [TheRandomLabs/RandomPatches#71]
So the latest version (1.19.1.1) for Minecraft 1.12.2 was supposed to fix the SpongeForge incompatibility, which it however didn't. Whenever I use SpongeForge 2838-7.1.7, the game crashes upon startup with this error:
https://pastebin.com/hcqmQyc6

The log says that Mixin is already being loaded, and I tried to narrow it down to which mod was causing the crash, and RandomPatches was the one I found out caused the crash.

**Comment by TheRandomLabs** [comment]
I can't reproduce this issue with just SpongeForge and RandomPatches, but before I go any further, could you see if 1.12.2-1.20.0.0 works?

**Comment by LokeYourC3PH** [comment]
Okay so I tried with version 1.20.0.1 that you posted 3 hours ago and it still crashes, I get this log (same as last one): https://pastebin.com/7wS0ptVR

**Comment by LokeYourC3PH** [comment]
The crash does not happen as long as Random Patches is not installed. I also tried removing some other mods before removing Random Patches, but for me it still crashes.

I should mention, the reason for why I have SpongeForge installed on the client, is because a mod called "SGCraft" (the remake called Stargate Network) is using SpongeForge because of Mixin. I tried removing it first because I thought it may be the culprit, but the game crashes with or without it, but if I remove Random Patches, everything is fine.

**Comment by LokeYourC3PH** [comment]
@TheRandomLabs Were you able to reproduce the issue with my logs?

**Comment by TheRandomLabs** [comment]
I wasn't able to reproduce the crash with these mods installed:
![image](https://user-images.githubusercontent.com/16755704/69312941-5cc74100-0c84-11ea-91ec-8acc7ce86927.png)
Can I have a `debug.log`?

**Comment by LokeYourC3PH** [comment]
@TheRandomLabs Yeah sure, here you go:
[debug.log](https://github.com/TheRandomLabs/RandomPatches/files/3873265/debug.log)

If you want, I can send you the modpack I threw together so that you can reproduce the issue if you want.

**Comment by seancrain** [comment]
@LokeYourLord I'm assuming your Sponge environment is serverside. I can tell you that the reason it's probably crashing is OptiFine, which is a clientside-only mod. Remove it from the server and then see if it loads.

**Comment by LokeYourC3PH** [comment]
> 
> 
> @LokeYourLord I'm assuming your Sponge environment is serverside. I can tell you that the reason it's probably crashing is OptiFine, which is a clientside-only mod. Remove it from the server and then see if it loads.

Nope, it's server and client side. I obviously don't have Optifine installed on the server, I wasn't born yesterday XD. Anyways, the crash happens on the client and server, and on the client I of course have Optifine installed, while I have Sponge installed both client and server side.

**Comment by TheRandomLabs** [comment]
I'm still unable to reproduce this crsah. Could I have the modpack?

**Comment by LokeYourC3PH** [comment]
@TheRandomLabs Here you go, I am using the latest Forge version (2847), and just add RandomPatches and you see what I mean: https://mega.nz/#!ItF2UKxD!PpT7UcL-K5aBQR3wvKEDynESw-oAvRTcAi5sc_zlVCM

**Comment by TheRandomLabs** [comment]
Thank you, I am able to reproduce the crash.

**Comment by TheRandomLabs** [comment]
For some reason, setting `client.dismountKeybind` to `false` prevents this crash. I have no idea why.
**EDIT:** Fixed.

**Comment by LokeYourC3PH** [comment]
Fix confirmed, thanks a lot :D
