### ISSUE TITLE
Crashes on startup Enigmatica 4 

### ISSUE THREAD

**Issue by Gunner76th** [TheRandomLabs/RandomPatches#73]
https://gist.github.com/Gunner76th/5f31f02eadd5cd3a267c0d7cdc117ee1

While using the GDLauncher to launch the modpack Enigmatical 4, the client crashes with the above crash for some reason. If I use the Mojang launcher however, while using the same JVM arguments and same Java, the modpack loads without issue. Both GDLauncher and Mojang launcher are pulling from the same directory. Literally the only difference is the launcher software.

**Comment by TheRandomLabs** [comment]
Looks like `STBImage` can't be found for whatever reason on GDLauncher.

**Comment by TheRandomLabs** [comment]
This doesn't seem to be an issue anymore.
