### ISSUE TITLE
[Suggestion] Fix backs of redstone torches, repeater torches, comparator torches and cacti not appearing from some angles

### ISSUE THREAD

**Issue by muzikbike** [TheRandomLabs/RandomPatches#74]
Since this mod fixes end portal blocks being invisible from underneath I figured it might be a good idea to suggest fixing some related cases of blocks being invisible from certain angles.

- Redstone wire has no bottom texture (MC-109850, fixed in 1.16)
![2019-12-14_15 10 55](https://user-images.githubusercontent.com/52297970/70850679-01543180-1e85-11ea-8737-c9dbb260b5dd.png)

- Back faces of redstone torches and cacti don't appear
![2019-12-14_15 11 27](https://user-images.githubusercontent.com/52297970/70850689-1761f200-1e85-11ea-8fa6-5e20957ec5f0.png)

**Comment by TheRandomLabs** [comment]
Thanks for the suggestions! I'll look at these.

**Comment by muzikbike** [comment]
Also, if you use setblock to place an isolated nether portal block, it won't have any top or bottom textures, nor any textures on the narrower sides. Not exactly sure if this should be fixed since it can't be encountered under survival conditions without bugs but it's something.

**Comment by muzikbike** [comment]
Another thing to mention is that I've managed to get MC-3366 reopened, so you could post the fix from the mod there as a code analysis

**Comment by muzikbike** [comment]
Just one more missing bottom face: https://bugs.mojang.com/browse/MC-120335

(Also fixed in 1.16, so not much point)

**Comment by muzikbike** [comment]
since these are all asset issues, is it really worth having a mod fix them? it'd make much more sense for a resource pack to do this instead

**Comment by TheRandomLabs** [comment]
I agree that having a separate resource pack is a great idea, perhaps for those who do not want to install a mod loader. On the other hand, mods can also include resources, and I suppose some would find it convenient to have those fixes bundled with the mod. Regardless, if you make a separate branch for 1.16 for [VanillaFixes](https://github.com/muzikbike/VanillaFixes), I'd be happy to recommend it. 😄 
**EDIT:** I had a brief look at VanillaFixesD, CrossFix, RandRotPlus and ActuallyPolished as well. Nice!

**Comment by TheRandomLabs** [comment]
Closing for now, since VanillaFixes seems to do the job.
