### ISSUE TITLE
[Suggestion] Make more controls toggleable

### ISSUE THREAD

**Issue by muzikbike** [TheRandomLabs/RandomPatches#75]
Currently the mod adds in the ability to rebind the narrator, which is an absolute lifesaver. I figured if this is able to be rebound, it might be worth making the rest of the non-rebindable vanilla controls be able to be rebound as well.

- F1
- F3
- F3 + D
- F3 + F
- F3 + G
- F3 + H
- F3 + I
- F3 + N
- F3 + P
- F3 + Q
- F3 + T
- F3 + Esc

There's also Esc itself, but I'm not sure if it'd be possible to allow that to be rebound.

**Comment by TheRandomLabs** [comment]
I didn't implement these because of the existence of [ReBind](https://www.curseforge.com/minecraft/mc-mods/rebind), but I'll consider it now since ReBind is still on 1.12.2.

**Comment by TheRandomLabs** [comment]
In the rewrite, I've implemented configurable key bindings for toggling the GUI and debug info as well as pausing and unpausing the game, but the F3 actions are too much of a hassle to deal with, and I think it's probably a good idea to leave Escape as the key for closing GUI screens.
