### ISSUE TITLE
Crash between Extra Utilities & Random Patches

### ISSUE THREAD

**Issue by NielsPilgaard** [TheRandomLabs/RandomPatches#76]
Hello!
It looks like RandomPatches makes a change that the Extra Utilities Auto User isn't too fond of.
Crash: https://gist.github.com/MCEventHorizon/126a95ad0954b81eac5336698e9ae6cb

Original issue: https://github.com/NillerMedDild/Enigmatica2ExpertSkyblock/issues/532

**Comment by TheRandomLabs** [comment]
RandomPatches 1.20.1.0 seems to fix this. Can you confirm?

**Comment by NielsPilgaard** [comment]
Yep that fixes it, thank you :)
