### ISSUE TITLE
Minecraft window title does not change

### ISSUE THREAD

**Issue by Yoosk** [TheRandomLabs/RandomPatches#79]
When trying to change Minecraft window title in 1.15.2, it does stay on default one.

randompatches-1.15.2-1.21.0.1.jar
forge-31.0.14

**Comment by TheRandomLabs** [comment]
Ah, this is because Minecraft now changes the window title depending on context.

**Comment by TheRandomLabs** [comment]
I've introduced another configuration option, `window.titleWithActivity`. It takes two arguments: the Minecraft version and the current activity. For example, in `"Modpack - %2$s"`, the `%2$s` would be replaced by the current activity.
