### ISSUE TITLE
Crash 1.4.1.0

### ISSUE THREAD

**Issue by JosEffigy** [TheRandomLabs/RandomPatches#8]
https://paste.dimdev.org/tobumohuqo.mccrash
suspected conflict with rebind narrator

**Comment by TheRandomLabs** [comment]
RandomPatches implements its own Toggle Narrator keybind. I did forget to make the feature disable itself if Rebind Narrator is installed though.

**Comment by TheRandomLabs** [comment]
This should be fixed in 1.12.2-1.4.1.1.
