### ISSUE TITLE
[1.15.2] Random Patches config resets to default

### ISSUE THREAD

**Issue by NielsPilgaard** [TheRandomLabs/RandomPatches#81]
On Minecraft 1.15.2 with `randompatches-1.15.2-1.21.1.0`, the config resets every time I launch the game.

### Versions
- randompatches-1.15.2-1.21.1.0
- Forge-1.15.2-31.1.0

**Comment by TheRandomLabs** [comment]
Could I have a `debug.log`? I'm having trouble reproducing this.

**Comment by NielsPilgaard** [comment]
Sure thing, I'll do not in about 4 hours :)

**Comment by NielsPilgaard** [comment]
Dammit, this was my mistake - I have DefaultSettings installed which overrode my changes, I was editing the wrong file pretty much. Sorry for the bother.
