### ISSUE TITLE
[1.15.2] XML_ERROR_PARSING

### ISSUE THREAD

**Issue by ProsperCraft** [TheRandomLabs/RandomPatches#82]
On startup-
https://gist.github.com/ProsperCraft/1b247b74400564322a2067912a1fc5fc

Full log-
Log-
[latest.log](https://github.com/TheRandomLabs/RandomPatches/files/4210676/latest.log)

Forge 31.1.12
randompatches-1.15.2-1.21.1.1.jar

**Comment by TheRandomLabs** [comment]
Does the issue persist when RandomPatches is removed?

**Comment by ProsperCraft** [comment]
No.

**Comment by TheRandomLabs** [comment]
I'm not getting this error. It doesn't look like it should be a concern, either. I'll reopen this if I find anything else.
