### ISSUE TITLE
Randompatches 1.12.2 - 1.22.0 on Allthemods expert remastered, login timers don't change.

### ISSUE THREAD

**Issue by Pyritefoolsgold** [TheRandomLabs/RandomPatches#83]
Basically what the title says. We installed randompatches hoping to make it easier to log in, on both the server and client side. Despite setting the login timer to 900 and keepalive timer to 180, I consistently time out after taking less than 2 minutes of login time.

**Comment by TheRandomLabs** [comment]
Could I have a `debug.log`, please?

**Comment by Pyritefoolsgold** [comment]
Is this what you're looking for?

https://paste.ee/p/uaDZu

I made this log immediately after timing out.

If you need something from the server-side, I'll have to wait until I can ask the server owner.

**Comment by TheRandomLabs** [comment]
I need the `debug.log` in the server's `logs` folder.

**Comment by Pyritefoolsgold** [comment]
We didn't find a debug.log file in the logs folder. I've had the server admin send me all the logs that were there.

I've uploaded a zip file with all the logs, if that works for you.
[ATM Server logs.zip](https://github.com/TheRandomLabs/RandomPatches/files/4217192/ATM.Server.logs.zip)

**Comment by TheRandomLabs** [comment]
Thank you. I'll see what I can do.

**Comment by HariboTer** [comment]
I have the exact same problem - playing with a large amount of mods, login attempts alway time out within a minute despite it being all set to 900 in the RandomPatches config :-(
Here's the corresponding debug.log file, I hope it helps to find the issue.

[debug.zip](https://github.com/TheRandomLabs/RandomPatches/files/4241875/debug.zip)

**Comment by TheRandomLabs** [comment]
I made quite the stupid mistake, it seems. I apologise. It should be fixed now. :)
