### ISSUE TITLE
[1.8.9] Potions in inventory crash game in singleplayer

### ISSUE THREAD

**Issue by leetfin** [TheRandomLabs/RandomPatches#85]
Potions in inventory crash game in singleplayer.

**Comment by TheRandomLabs** [comment]
Crash report?

**Comment by leetfin** [comment]
[crash-2020-04-01_18.59.34-client.txt](https://github.com/TheRandomLabs/RandomPatches/files/4432241/crash-2020-04-01_18.59.34-client.txt)
