### ISSUE TITLE
1.15 - Crashes when viewing recipe in FTB Questing questbook

### ISSUE THREAD

**Issue by MeltPels** [TheRandomLabs/RandomPatches#86]
I suspect RandomPatches crashes the client when you view a recipe in the Questbook.

https://pastebin.com/9qkz9rgg

I've also reported this to the FTB Questbook github.
https://github.com/FTBTeam/FTB-Quests/issues/398

**Comment by TheRandomLabs** [comment]
This isn't RandomPatches. The method signature of `GuiHelper#drawItem` has been [changed ](https://github.com/FTBTeam/FTB-GUI-Library/blob/master/src/main/java/com/feed_the_beast/mods/ftbguilibrary/widget/GuiHelper.java#L184) to use `int`s instead of `double`s.
