### ISSUE TITLE
Bottom of end portal not culled by solid blocks

### ISSUE THREAD

**Issue by muzikbike** [TheRandomLabs/RandomPatches#87]
![2020-04-07_19 26 57](https://user-images.githubusercontent.com/52297970/78705756-df842c00-7905-11ea-9742-0c0d4f849f38.png)

**Comment by TheRandomLabs** [comment]
I can't reproduce this. Let me know if this is still an issue.

**Comment by muzikbike** [comment]
Nope i'm definitely still experiencing this in the latest 1.15.2 build:
![2020-07-07_09 18 21](https://user-images.githubusercontent.com/52297970/86746369-ede00200-c032-11ea-905b-3d53668d6c9b.png)
![2020-07-07_09 18 27](https://user-images.githubusercontent.com/52297970/86746378-efa9c580-c032-11ea-9197-9805931d697b.png)

**Comment by muzikbike** [comment]
why is this showing up in my list of closed issues, maybe this comment will fix it

**Comment by TheRandomLabs** [comment]
Moved to #146.

**Comment by muzikbike** [comment]
Should be irrelevant for 1.17+ onwards anyway
