### ISSUE TITLE
Crash with 1.12.2-1.5.0.0

### ISSUE THREAD

**Issue by comp500** [TheRandomLabs/RandomPatches#9]
Seems to be with WindowIconHandler.setWindowIcon. Occurs with no other mods, just forge.

Forge: 14.23.4.2711
Log: [https://paste.ee/p/82LXe](https://paste.ee/p/82LXe)

**Comment by Zarepheth** [comment]
I'm having the same problem. The game starts loading, and quickly fails with the same error as @comp500.

Log file: [https://paste.ee/p/nehbq](https://paste.ee/p/nehbq)

The game works if I remove RandomPatches 1.5.0.0 and return to using the older RandomPatches 1.4.1.1.

**Comment by TheRandomLabs** [comment]
Looks like I forgot to see if the vanilla icon worked during testing. This should be fixed in 1.12.2-1.5.0.1.

**Comment by Gunner76th** [comment]
@comp500 amd @Zarepheth Please do not set an expiration limit on crash reports when posting them like this. Both of your crash reports are now expired and removed, meaning that I am unable to compare your issue with mine. Please either make sure that you set it to not expire on Paste.ee or you use gist.github.com to post crash reports (or a similar site)
