### ISSUE TITLE
randompatches-1.12.2-1.21.0.1 incompatibility with LiteLoader-1.12.1-00

### ISSUE THREAD

**Issue by jamesonknutson** [TheRandomLabs/RandomPatches#92]
First time posting a bug report / issue on Git, apologies if I miss any relevant information.

Using RandomPatches version: randompatches-1.12.2-1.21.0.1
Forge Version: forge-1.12.1-14.22.1.2478
LiteLoader Version: [1.12.1-00-SNAPSHOT](http://www.liteloader.com/download#snapshot_11210)
My LiteLoader version extends into my Forge version, so I am actually launching version **1.12.1-LiteLoader1.12.1-1.12.1-forge1.12.1-14.22.1.2478**.
Mods used: https://prnt.sc/s0q99f

Issue: When launching the game, Forge loads properly & all the Forge mods I am using are initialized properly. LiteLoader does not seem to load whatsoever, and all the LiteLoader mods I am using are not loaded either. I have attached what I believe to be the relevant logs with the stack trace spawned by this error.

[latest.log](https://github.com/TheRandomLabs/RandomPatches/files/4489217/latest.log)

If any further information is required please let me know.

**Comment by jamesonknutson** [comment]
Attaching liteloader log from /liteconfig/liteloader.txt in case it is of significance.

[liteloader.log](https://github.com/TheRandomLabs/RandomPatches/files/4489249/liteloader.log)

**Comment by jamesonknutson** [comment]
This issue seems to be bandaid-fixed by disabling RandomPatches' client-sided option "patch minecraft class", then restarting Minecraft.

**Comment by TheRandomLabs** [comment]
That option is now automatically disabled when LiteLoader is detected.
