### ISSUE TITLE
Need help connection time outs.

### ISSUE THREAD

**Issue by IchigoGames** [TheRandomLabs/RandomPatches#95]
this may get closed as i do not really have enough information to go on but for a long time now i have been having people tell me they cant connect to server i check console on server and theres all it say is they timed out some times a player is able to join once and then unable to join the next time this happens on 2 server hosts running my pack i looked everything when i found that this mod a mod in my pack has settings for connection time outs i changed them to give player longer time to connect but still not luck is there anything you know that could help ?

Minecraft 1.15.2
Forge 31.1.50
randompatches-1.15.2-1.21.1.2
my modpack https://www.curseforge.com/minecraft/modpacks/the-endless-frontier
let me know if you need any logs or anything.

**Comment by TheRandomLabs** [comment]
Closing in favour of #94.
