### ISSUE TITLE
Too long to connect - 1.15.2-1.21.1.2.jar

### ISSUE THREAD

**Issue by JayWood** [TheRandomLabs/RandomPatches#96]
Just wanted to say I'm having the same issue as #94 I believe. However I'm using a different modpack, but same mod version. 

I'm a dev by day ( though not java ) so hopefully the slew of logs I can provide may be more helpful than noise. I was going to reply to 94 but didn't want to hijack the thread and given the amount of info below, I feel it may have given anyone reading it a seizure 😄.

I have a dedibox currently I'm willing to give you access to as the MC user if you'd like as well. Anyhow, here's the ton of info below.

### Modpack: 
* https://www.curseforge.com/minecraft/modpacks/plunger

### Server Spec:
* Intel i7-4790K (4c/8th)
* 16GB DDR3 1333MHz ( 8G allocated by startup script )
* 120 GB SSD
* Server is a dedicated box from SoYouStart ( ovh subsidiary ).

I've ran servers with SYS before and have some experience setting them up, but never ran into this issue before.

### Client Spec:
* AMD FX 8120 ( 8c 3.x GHz )
* 32G Ram
* GTX 1060 Gfx card.
* No Optifine installed
* Vsync disabled ( read about an issue w/ vsync too just in case )
* 100Mb Down/ 10Mb up ( net )
* Twitch launcher
* Custom launch params - https://gist.github.com/JayWood/90fe7ae1efa6a562708cce89fd51cc40
* Figured it was garbage collection or something taking too long (idk really) so I tried with **zero launch params**, still failed.

I figured I could bypass the timeout issue by disabling RandomPatches and set the java flag of `-Dforge.readTimeout=300` thinking that'd help, but nope. Had to do digging to find this - https://github.com/MinecraftForge/MinecraftForge/blob/1933d05e36245ef7461b29853b4854fa769a807f/patches/minecraft/net/minecraft/network/NetworkSystem.java.patch#L7

Either way, that didn't help, I'm only a hobby Java dev, still learning new things. If it were PHP I could fix it no problem I'm sure 😄 but I can't make heads/tails of some of the java code in this plugin to really provide any additional help. So, here's all the logs I can provide.

### Before trying to connect w/ the client:
* **debug.log** - https://gist.github.com/JayWood/abed9176d3fab6a928c4dc37ca3ca5b5
* **latest.log** - https://gist.github.com/JayWood/a3de3a3a123daceff49c8c271a645ff4
* **randompatches.toml** - https://gist.github.com/JayWood/520fb319774da1b0aaad21e1a08c0da8

### After trying to connect:
* **debug.log** - https://gist.github.com/JayWood/4adf20a4d98a4f8636b51b90553be2fe
* **latest.log** - https://gist.github.com/JayWood/b71a7a0ea432b81cfec873577e1034d6

### Client log:
* **latest.log** - https://gist.github.com/JayWood/81163afd5e02d8056f3efde69123043a

For some reason the Transformer method didn't make it into the log, but this is from the console output:

```
[19:09:52] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (midnight): All chunks are saved
> [RandomPatches ServerLoginNetHandler Transformer]: Patching method: func_73660_a (func_73660_a)
[19:12:21] [User Authenticator #1/INFO] [minecraft/ServerLoginNetHandler]: UUID of player phyrax is bee7f9c0-a094-4c3a-9f38-baf6d4270139
[19:12:21] [Netty Epoll Server IO #2/INFO] [journeymap/]: Dev Mode?
[19:12:53] [Server thread/INFO] [minecraft/ServerLoginNetHandler]: com.mojang.authlib.GameProfile@7f7aed62[id=bee7f9c0-a094-4c3a-9f38-baf6d4270139,name=phyrax,properties={textures=[com.mojang.authlib.properties.Property@2f08eea2]},legacy=false] (/47.133.44.204:51497) lost connection: Timed out
[19:20:00] [Server thread/INFO] [tombstone/]: The player  has successfully been saved
```

If you've read this far... 🥳 thank you, and I hope it helps. I'm happy to help debug this live or on a call of any sort if you want ( I know how much of a pain it is debugging things sometimes ). Thanks in advance, and again, I hope this isn't just noise.

**Comment by davidhepp** [comment]
I'm having the exact same issue with the same modpack. Changing configs doesn't seem to affect the login timeout, as it always kicks after 30 seconds.

**Comment by Darkfiend009** [comment]
A player on my server is experiencing this as well.

**Comment by SDUBZ** [comment]
@TheRandomLabs any thoughts as i ahve a few users even on my own modpack too with users connecting to server

**Comment by davidhepp** [comment]
> @TheRandomLabs any thoughts as i ahve a few users even on my own modpack too with users connecting to server

Try removing cyclic.

**Comment by SDUBZ** [comment]
i dont use that terrible mod @Daskyy

**Comment by bribri69** [comment]
Hi ! I have the same problem... Changing config doesn't affect the timeout.

**Comment by mr-poyo** [comment]
I'm also receiving this problem with my own custom pack. No matter what I set loginTimeout to in the config, It's still kicking me out on login. For me, it feels less than 30 seconds.

**Comment by TheRandomLabs** [comment]
Closing in favor of #94.
