### ISSUE TITLE
"[Warn] ... does not have a MCVersion annotation.." + Error

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [TheRandomLabs/RandomPatches#97]
Forge: forge-1.12.2-14.23.5.2847-universal
Mod Version: randompatches-1.12.2-1.21.0.3
Mods List: RandomPatches (only)
latest.log: https://gist.github.com/pinkpig3777/d668ca627c9691fc7d1fc7dc0e538ad4
debug.log: https://gist.github.com/pinkpig3777/cf97fbc8a8918aa1ad94cfd77cf98431
Warning Message: 
[10:36:37] [main/WARN] [FML]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft

I noticed[ this issue post](https://github.com/TheRandomLabs/RandomPatches/issues/89) has the same line in it. Thus I tried the solutions you offered one at a time:
Setting `B:patchMinecraftClass=false` did not fix the issue.
Re-enabling that option and setting `patchTitleScreenOnDisconnect=false` did not fix the issue.

Thus I've re-enabled both.

Additionally, on [CatServer](https://github.com/Luohuayu/CatServer) it shows this error (which starts with the SAME warning message):
https://gist.github.com/pinkpig3777/09266604711fcf1184ac902bbcbb8cf5
CatServer's latest.log: https://gist.github.com/pinkpig3777/8ae9dedbf6d47fc18b1299481cf6c373
CatServer's debug.log: https://gist.github.com/pinkpig3777/a89b2ab81543a604a237af20a9673581

**How can this issue be fixed?** I mainly use CatServer but compare any errors to normal Forge when I report issues. And both show the same warning message but CatServer gives additional errors afterwards.

Help would be greatly appreciated, thank you!

**Comment by TheRandomLabs** [comment]
RandomPatches intentionally does not have an `MCVersion` annotation, as it does not allow the specification of multiple versions. The 1.12.2 version of RandomPatches is written to work on all Forge versions from 1.8 to 1.12.2, and an `MCVersion` annotation would prevent this. The message can safely be ignored.

**Comment by TheRandomLabs** [comment]
Oh, and the second error can be fixed by disabling `misc.portalBucketReplacementFix`. It's probably a conflict with Spigot.

**Comment by PiggiesGoSqueal** [comment]
> 
> 
> Oh, and the second error can be fixed by disabling `misc.portalBucketReplacementFix`. It's probably a conflict with Spigot.

I believe that fixed it. Thank you!
