### ISSUE TITLE
randompatches-1.12.2-1.21.0.3 - ReadTimeoutException : Null (login timer doesn't change)

### ISSUE THREAD

**Issue by cylaw92** [TheRandomLabs/RandomPatches#98]
A handful of players (myself included) stumbled upon similar issues documented in #83 where the default "readTimeout" and "loginTimeout" value in RandomPatches don't seem to take effect and consistently disconnecting players after 30 seconds (ReadTimeoutException : null)
![ss+(2020-05-02+at+03 13 49)](https://user-images.githubusercontent.com/62367497/80960862-4f6dcf80-8e3c-11ea-8dd0-bf736a2feac6.png)
Server side log will display this error:
> [14:59:31] [Netty Epoll Server IO #16/ERROR] [FML]: NetworkDispatcher exception
> io.netty.handler.timeout.ReadTimeoutException: null

A couple things we've tried:
1) Installing the latest version (1.21.0.3) on both client and server with stock config (after noticing it's a targeted fix at #83 (5d4e52f))
2) Manually added in JVM argument upon start up (-Dfml.readTimeout=90 -Dfml.loginTimeout=900)
3) Fresh installs, stock configs
4) Different launchers (Twitch, GDlauncher, MultiMC)

But the patch doesn't seem to take effect and still giving us the same error.
1) Maybe there's another mod that overwrites those values? For reference, we're playing the modpack, All the Mods 3 Remix ([modlist](http://puu.sh/FG5bG.txt))
2) Modpack might be too heavy (factoring in distance to host), but doesn't explain the 30 seconds readTimeout
3) Curious what the fix 5d4e52f actually does?
4) There's a handful of other players who face no issue on this, no consistent pattern but those who got the error will get it consistently

Let me know what other documents you need, from client or server side. Feel free to merge and/or reopen with the mentioned issue thread.
Thanks for your help!

**Comment by TheRandomLabs** [comment]
That commit fixed the login timeout not being patched. As far as I can tell, this is related to the read timeout, so it wouldn't be relevant.

**Comment by cylaw92** [comment]
Ah my mistakes then, so any direction we should be looking at?
Thanks for the reply!

**Comment by TheRandomLabs** [comment]
The latest release may fix this. :)

**Comment by TheRandomLabs** [comment]
Let me know if this is still a problem.
