### ISSUE TITLE
Client crash on server when breaking dirt

### ISSUE THREAD

**Issue by Darkfiend009** [TheRandomLabs/RandomPatches#99]
Crash Log: https://pastebin.com/xTjHFj0B

MC Version: 1.15.2
Forge: 31.1.74
RandomPatches: 1.21.1.2
Modpack: Parity

The crash happens when a player is breaking dirt. It is not consistent. However, it has happened to 2 different players on the server. The crash reports were identical. If the player reconnects and tries to break that same block, they will crash again.

**Comment by TheRandomLabs** [comment]
This isn't an issue with RandomPatches. It might be CoFH Lib.
